import {
  RABBY_MOBILE_KR_PWD as RABBY_MOBILE_KR_PWD2,
  RABBY_MOBILE_KR_PWD_0617 as RABBY_MOBILE_KR_PWD2_0617,
} from '@env';

export const RABBY_MOBILE_KR_PWD = RABBY_MOBILE_KR_PWD2;

export const RABBY_MOBILE_KR_PWD_0617 = RABBY_MOBILE_KR_PWD2_0617;
