type KeychainCommonModule = typeof import('./keychainCommon');

const DEBUG_MODULE_NAME = 'RabbyKeychainDebug';

function makeBrokenBiometricsNativeState() {
  return {
    hasEntry: true,
    hasUsername: true,
    hasPassword: true,
    hasCipherStorageMarker: false,
    isCipherStorageMarkerMissing: true,
    storedUsernameBase64: 'Y2lwaGVydGV4dA==',
    storedPasswordBase64: 'Y2lwaGVydGV4dA==',
    storedCipherStorageMarkerValue: null,
    storedCipherStorageName: 'KeystoreRSAECB',
    resolvedCipherStorageName: 'KeystoreRSAECB',
    candidateCipherStorageNames: ['KeystoreRSAECB'],
    cipherStorageResolutionStrategy: 'legacy-fallback',
    usernameByteSize: 256,
    passwordByteSize: 512,
    keystoreAlias: 'com.debank',
    hasKeystoreAlias: true,
    keystoreKeyAlgorithm: 'RSA',
    keystoreSecurityLevel: null,
    keystoreInsideSecureHardware: null,
    keystoreUserAuthenticationRequired: true,
    keystoreUserAuthenticationValidityDurationSeconds: null,
    keystoreUserAuthenticationType: null,
    keystoreBlockModes: null,
    keystorePurposes: null,
    keystoreIsCompatibleWithCurrentCipher: true,
    keystorePublicKeySha256: null,
    keystoreDebugErrorMessage: null,
  };
}

function loadKeychainCommon({
  getGenericPasswordError,
  decryptError,
  promptError,
  fallbackSucceeds = false,
  nativeDebugState = makeBrokenBiometricsNativeState(),
}: {
  getGenericPasswordError?: Error;
  decryptError?: Error;
  promptError?: Error;
  fallbackSucceeds?: boolean;
  nativeDebugState?: Record<string, unknown>;
}) {
  jest.resetModules();

  const keychainModule = {
    getGenericPassword: jest.fn(async () => {
      if (getGenericPasswordError) throw getGenericPasswordError;
      return {
        password: 'fixture-encrypted-payload',
        storage: 'KeystoreAESGCM_NoAuth',
      };
    }),
    setGenericPassword: jest.fn(async () => true),
    resetGenericPassword: jest.fn(async () => true),
    getSupportedBiometryType: jest.fn(async () => 'Fingerprint'),
    isPasscodeAuthAvailable: jest.fn(async () => true),
    ACCESSIBLE: { WHEN_UNLOCKED_THIS_DEVICE_ONLY: 'accessible' },
    ACCESS_CONTROL: {
      BIOMETRY_CURRENT_SET: 'biometry-current-set',
      DEVICE_PASSCODE: 'device-passcode',
      BIOMETRY_ANY_OR_DEVICE_PASSCODE: 'biometry-any-or-device-passcode',
      BIOMETRY_CURRENT_SET_OR_DEVICE_PASSCODE:
        'biometry-current-set-or-device-passcode',
    },
    AUTHENTICATION_TYPE: {
      BIOMETRICS: 'biometrics',
      DEVICE_PASSCODE_OR_BIOMETRICS: 'device-passcode-or-biometrics',
    },
    SECURITY_RULES: { AUTOMATIC_UPGRADE: 'automatic-upgrade' },
  };
  const toastShow = jest.fn();
  const markStage = jest.fn();
  const recordPayload = jest.fn();
  const decrypt = jest.fn(
    async (
      _code: string,
      _payload: string,
      observer?: (event: {
        phase: string;
        outcome: string;
        errorKind?: string;
      }) => void,
    ) => {
      const fail =
        decryptError && !(fallbackSucceeds && _code === 'RABBY_MOBILE_CODE');
      observer?.({
        phase: 'envelope_json',
        outcome: fail ? 'failed' : 'succeeded',
        ...(fail ? { errorKind: 'syntax' } : {}),
      });
      if (fail) throw decryptError;
      return { password: 'fixture-plain-password' };
    },
  );
  const simplePrompt = jest.fn(async () => {
    if (promptError) throw promptError;
    return { success: true };
  });

  jest.doMock('react-native', () => ({
    Platform: { OS: 'android', Version: 34 },
    NativeModules: {
      [DEBUG_MODULE_NAME]: {
        debugGetGenericPasswordStateForOptions: jest.fn(
          async () => nativeDebugState,
        ),
      },
    },
  }));
  jest.doMock('react-native-biometrics', () => ({
    __esModule: true,
    default: jest.fn(() => ({ simplePrompt })),
  }));
  jest.doMock('react-native-device-info', () => ({
    __esModule: true,
    default: { isPinOrFingerprintSet: jest.fn(async () => true) },
  }));
  jest.doMock('@/utils/i18n', () => ({
    __esModule: true,
    default: { t: (key: string) => key },
  }));
  jest.doMock('@/constant/env', () => ({
    DEFAULT_RABBY_MOBILE_CODE: 'RABBY_MOBILE_CODE',
  }));
  jest.doMock('@/utils/logger', () => ({
    logger: { info: jest.fn(), warn: jest.fn() },
  }));
  jest.doMock('@/components2024/Toast', () => ({
    toast: { show: toastShow },
  }));
  jest.doMock('../storage/mmkvInstances', () => ({
    keychainMMKV: { getNumber: jest.fn(() => 1), set: jest.fn() },
  }));
  jest.doMock('../storage/mmkvConstants', () => ({
    KEYCHAIN_MMKV_KEYS: { AUTHENTICATION_TYPE: 'AUTHENTICATION_TYPE' },
  }));
  jest.doMock('@/core/serviceApi/appEncryptor', () => ({
    appEncryptorApi: {
      encrypt: jest.fn(async () => 'encrypted'),
      decrypt,
    },
  }));
  jest.doMock('@/core/serviceApi/preference', () => ({
    getPasswordIsAutoGeneratedSnapshot: jest.fn(() => false),
  }));
  jest.doMock('./lock', () => ({
    safeVerifyPasswordAndUpdateUnlockTime: jest.fn(async () => ({
      success: true,
    })),
    updateUnlockTime: jest.fn(),
    clearCustomPassword: jest.fn(async () => ({})),
  }));
  jest.doMock('./androidBiometricsRegression', () => ({
    getAndroidBiometricSecurityLevelOptions: jest.fn(() => ({})),
  }));
  jest.doMock('../utils/diagnosticEnv', () => ({
    isNonProductionDiagnosticsEnabled: false,
  }));
  jest.doMock('@/utils/walletUnlockDiagnostics', () => ({
    markWalletUnlockDiagnosticStage: markStage,
    recordWalletUnlockPayloadDiagnostic: recordPayload,
  }));

  let module: KeychainCommonModule | undefined;
  jest.isolateModules(() => {
    module = require('./keychainCommon');
  });

  return {
    module: module!,
    keychainModule,
    toastShow,
    markStage,
    simplePrompt,
    recordPayload,
    decrypt,
  };
}

describe('core/apis/keychainCommon', () => {
  it.each([false, true])(
    'keeps candidate order/result and records each candidate (fallback success: %s)',
    async fallbackSucceeds => {
      const failure = new SyntaxError('synthetic private error');
      const { module, keychainModule, recordPayload, decrypt } =
        loadKeychainCommon({
          decryptError: failure,
          fallbackSucceeds,
        });
      module.makeSecureKeyChainInstance({ salt: 'fixture-salt' });
      const api = module.createBusinessKeychainApi({
        keychainModule: keychainModule as unknown as Parameters<
          KeychainCommonModule['createBusinessKeychainApi']
        >[0]['keychainModule'],
        debugNativeModuleName: DEBUG_MODULE_NAME,
        sourceLabel: 'test',
      });
      const request = api.requestGenericPassword({
        purpose: module.RequestGenericPurpose.DECRYPT_PWD,
        walletUnlockDiagnosticsAttemptId: 'fixture-attempt',
        shouldAttachTrustedVaultKeyString: false,
        skipPostDecryptKeychainRewrite: true,
      });
      if (fallbackSucceeds)
        await expect(request).resolves.toMatchObject({ actionSuccess: true });
      else await expect(request).rejects.toBe(failure);
      expect(decrypt.mock.calls.map(call => call[0])).toEqual([
        'fixture-salt',
        'RABBY_MOBILE_CODE',
      ]);
      expect(recordPayload).toHaveBeenCalledWith('fixture-attempt', 1, 2, {
        phase: 'envelope_json',
        outcome: 'failed',
        errorKind: 'syntax',
      });
      expect(recordPayload).toHaveBeenCalledWith(
        'fixture-attempt',
        2,
        2,
        expect.objectContaining({
          phase: 'envelope_json',
          outcome: fallbackSucceeds ? 'succeeded' : 'failed',
        }),
      );
      expect(JSON.stringify(recordPayload.mock.calls)).not.toContain(
        'fixture-plain-password',
      );
      expect(JSON.stringify(recordPayload.mock.calls)).not.toContain(
        'synthetic private error',
      );
      expect(keychainModule.setGenericPassword).not.toHaveBeenCalled();
      expect(keychainModule.resetGenericPassword).not.toHaveBeenCalled();
    },
  );
  it.each(['native', 'prompt', 'payload', 'wallet', 'success'] as const)(
    'keeps diagnostics at the actual %s boundary without changing the request result',
    async boundary => {
      const failure = new Error('fixture failure');
      const { module, keychainModule, markStage } = loadKeychainCommon({
        getGenericPasswordError: boundary === 'native' ? failure : undefined,
        promptError: boundary === 'prompt' ? failure : undefined,
        decryptError: boundary === 'payload' ? failure : undefined,
      });
      module.makeSecureKeyChainInstance({ salt: 'fixture-salt' });
      const api = module.createBusinessKeychainApi({
        keychainModule: keychainModule as unknown as Parameters<
          KeychainCommonModule['createBusinessKeychainApi']
        >[0]['keychainModule'],
        debugNativeModuleName: DEBUG_MODULE_NAME,
        sourceLabel: 'test',
      });
      const onPlainPassword = jest.fn(async () => {
        if (boundary === 'wallet') throw failure;
      });
      const request = api.requestGenericPassword({
        purpose: module.RequestGenericPurpose.DECRYPT_PWD,
        walletUnlockDiagnosticsAttemptId: 'fixture-attempt',
        shouldAttachTrustedVaultKeyString: false,
        skipPostDecryptKeychainRewrite: true,
        onPlainPassword,
      });
      if (boundary === 'success') {
        await expect(request).resolves.toMatchObject({ actionSuccess: true });
      } else {
        await expect(request).rejects.toBe(failure);
      }
      const finalStage = {
        native: 'keychain_native_get',
        prompt: 'system_auth_prompt',
        payload: 'decrypt_password_payload',
        wallet: 'plain_password_callback',
        success: 'post_decrypt_keychain_rewrite',
      }[boundary];
      expect(markStage.mock.calls.at(-1)?.[1]).toBe(finalStage);
      expect(
        markStage.mock.calls.every(([id]) => id === 'fixture-attempt'),
      ).toBe(true);
      expect(JSON.stringify(markStage.mock.calls)).not.toContain(
        'fixture-plain-password',
      );
      expect(JSON.stringify(markStage.mock.calls)).not.toContain(
        'fixture-encrypted-payload',
      );
      expect(keychainModule.setGenericPassword).not.toHaveBeenCalled();
      expect(keychainModule.resetGenericPassword).not.toHaveBeenCalled();
    },
  );

  it('summarizeKeychainDebugState strips stored credentials', () => {
    const { module } = loadKeychainCommon({
      getGenericPasswordError: new Error('unrelated'),
    });

    const summarized = module.summarizeKeychainDebugState(
      makeBrokenBiometricsNativeState() as any,
    );

    expect(summarized).not.toHaveProperty('storedUsernameBase64');
    expect(summarized).not.toHaveProperty('storedPasswordBase64');
    expect(summarized.hasStoredUsernameBase64).toBe(true);
    expect(summarized.hasStoredPasswordBase64).toBe(true);
    expect(summarized).toMatchObject({
      resolvedCipherStorageName: 'KeystoreRSAECB',
      keystoreKeyAlgorithm: 'RSA',
    });
  });

  it('broken biometrics entry error carries a sanitized debugState', async () => {
    const { module, keychainModule } = loadKeychainCommon({
      getGenericPasswordError: new Error(
        'msg: RSA decrypt failed on both current and legacy paths',
      ),
    });
    module.makeSecureKeyChainInstance({ salt: 'salt' });
    const api = module.createBusinessKeychainApi({
      keychainModule: keychainModule as any,
      debugNativeModuleName: DEBUG_MODULE_NAME,
      sourceLabel: 'test',
    });

    const error = await api
      .requestGenericPassword({})
      .catch(caught => caught as Error & Record<string, unknown>);

    expect(module.isBrokenBiometricsEntryError(error)).toBe(true);
    const debugState = (error as Record<string, any>).debugState;
    expect(debugState).toBeTruthy();
    expect(debugState).not.toHaveProperty('storedUsernameBase64');
    expect(debugState).not.toHaveProperty('storedPasswordBase64');
    expect(debugState.hasStoredUsernameBase64).toBe(true);
    expect(debugState.hasStoredPasswordBase64).toBe(true);
    expect(debugState.resolvedCipherStorageName).toBe('KeystoreRSAECB');
  });

  it('passes through unrelated keychain errors without debugState', async () => {
    const { module, keychainModule } = loadKeychainCommon({
      getGenericPasswordError: new Error('msg: some other failure'),
    });
    module.makeSecureKeyChainInstance({ salt: 'salt' });
    const api = module.createBusinessKeychainApi({
      keychainModule: keychainModule as any,
      debugNativeModuleName: DEBUG_MODULE_NAME,
      sourceLabel: 'test',
    });

    const error = await api
      .requestGenericPassword({})
      .catch(caught => caught as Error & Record<string, unknown>);

    expect(module.isBrokenBiometricsEntryError(error)).toBe(false);
    expect((error as Record<string, unknown>).debugState).toBeUndefined();
  });
});
