type KeychainCommonModule = typeof import('./keychainCommon');

const DEBUG_MODULE_NAME = 'RabbyKeychainDebug';

function makeBrokenBiometricsNativeState() {
  return {
    hasEntry: true,
    hasUsername: true,
    hasPassword: true,
    hasCipherStorageMarker: false,
    isCipherStorageMarkerMissing: true,
    storedUsernameBase64: 'Y2lwaGVydGV4dA==',
    storedPasswordBase64: 'Y2lwaGVydGV4dA==',
    storedCipherStorageMarkerValue: null,
    storedCipherStorageName: 'KeystoreRSAECB',
    resolvedCipherStorageName: 'KeystoreRSAECB',
    candidateCipherStorageNames: ['KeystoreRSAECB'],
    cipherStorageResolutionStrategy: 'legacy-fallback',
    usernameByteSize: 256,
    passwordByteSize: 512,
    keystoreAlias: 'com.debank',
    hasKeystoreAlias: true,
    keystoreKeyAlgorithm: 'RSA',
    keystoreSecurityLevel: null,
    keystoreInsideSecureHardware: null,
    keystoreUserAuthenticationRequired: true,
    keystoreUserAuthenticationValidityDurationSeconds: null,
    keystoreUserAuthenticationType: null,
    keystoreBlockModes: null,
    keystorePurposes: null,
    keystoreIsCompatibleWithCurrentCipher: true,
    keystorePublicKeySha256: null,
    keystoreDebugErrorMessage: null,
  };
}

function loadKeychainCommon({
  getGenericPasswordError,
  nativeDebugState = makeBrokenBiometricsNativeState(),
}: {
  getGenericPasswordError: Error;
  nativeDebugState?: Record<string, unknown>;
}) {
  jest.resetModules();

  const keychainModule = {
    getGenericPassword: jest.fn(async () => {
      throw getGenericPasswordError;
    }),
    setGenericPassword: jest.fn(async () => true),
    resetGenericPassword: jest.fn(async () => true),
    getSupportedBiometryType: jest.fn(async () => 'Fingerprint'),
    isPasscodeAuthAvailable: jest.fn(async () => true),
    ACCESSIBLE: { WHEN_UNLOCKED_THIS_DEVICE_ONLY: 'accessible' },
    ACCESS_CONTROL: {
      BIOMETRY_CURRENT_SET: 'biometry-current-set',
      DEVICE_PASSCODE: 'device-passcode',
      BIOMETRY_ANY_OR_DEVICE_PASSCODE: 'biometry-any-or-device-passcode',
      BIOMETRY_CURRENT_SET_OR_DEVICE_PASSCODE:
        'biometry-current-set-or-device-passcode',
    },
    AUTHENTICATION_TYPE: {
      BIOMETRICS: 'biometrics',
      DEVICE_PASSCODE_OR_BIOMETRICS: 'device-passcode-or-biometrics',
    },
    SECURITY_RULES: { AUTOMATIC_UPGRADE: 'automatic-upgrade' },
  };
  const toastShow = jest.fn();

  jest.doMock('react-native', () => ({
    Platform: { OS: 'android', Version: 34 },
    NativeModules: {
      [DEBUG_MODULE_NAME]: {
        debugGetGenericPasswordStateForOptions: jest.fn(
          async () => nativeDebugState,
        ),
      },
    },
  }));
  jest.doMock('react-native-biometrics', () => ({
    __esModule: true,
    default: jest.fn(),
  }));
  jest.doMock('@/utils/i18n', () => ({
    __esModule: true,
    default: { t: (key: string) => key },
  }));
  jest.doMock('@/constant/env', () => ({
    DEFAULT_RABBY_MOBILE_CODE: 'RABBY_MOBILE_CODE',
  }));
  jest.doMock('@/utils/logger', () => ({
    logger: { info: jest.fn(), warn: jest.fn() },
  }));
  jest.doMock('@/components2024/Toast', () => ({
    toast: { show: toastShow },
  }));
  jest.doMock('../storage/mmkvInstances', () => ({
    keychainMMKV: { getNumber: jest.fn(() => 1), set: jest.fn() },
  }));
  jest.doMock('../storage/mmkvConstants', () => ({
    KEYCHAIN_MMKV_KEYS: { AUTHENTICATION_TYPE: 'AUTHENTICATION_TYPE' },
  }));
  jest.doMock('@/core/serviceApi/appEncryptor', () => ({
    appEncryptorApi: {
      encrypt: jest.fn(async () => 'encrypted'),
      decrypt: jest.fn(async () => ({})),
    },
  }));
  jest.doMock('@/core/serviceApi/preference', () => ({
    getPasswordIsAutoGeneratedSnapshot: jest.fn(() => false),
  }));
  jest.doMock('./lock', () => ({
    safeVerifyPasswordAndUpdateUnlockTime: jest.fn(async () => ({
      success: true,
    })),
    updateUnlockTime: jest.fn(),
    clearCustomPassword: jest.fn(async () => ({})),
  }));
  jest.doMock('./androidBiometricsRegression', () => ({
    getAndroidBiometricSecurityLevelOptions: jest.fn(() => ({})),
  }));
  jest.doMock('../utils/diagnosticEnv', () => ({
    isNonProductionDiagnosticsEnabled: false,
  }));
  jest.doMock('@/utils/walletUnlockDiagnostics', () => ({
    markWalletUnlockDiagnosticStage: jest.fn(),
  }));

  let module: KeychainCommonModule | undefined;
  jest.isolateModules(() => {
    module = require('./keychainCommon');
  });

  return { module: module!, keychainModule, toastShow };
}

describe('core/apis/keychainCommon', () => {
  it('summarizeKeychainDebugState strips stored credentials', () => {
    const { module } = loadKeychainCommon({
      getGenericPasswordError: new Error('unrelated'),
    });

    const summarized = module.summarizeKeychainDebugState(
      makeBrokenBiometricsNativeState() as any,
    );

    expect(summarized).not.toHaveProperty('storedUsernameBase64');
    expect(summarized).not.toHaveProperty('storedPasswordBase64');
    expect(summarized.hasStoredUsernameBase64).toBe(true);
    expect(summarized.hasStoredPasswordBase64).toBe(true);
    expect(summarized).toMatchObject({
      resolvedCipherStorageName: 'KeystoreRSAECB',
      keystoreKeyAlgorithm: 'RSA',
    });
  });

  it('broken biometrics entry error carries a sanitized debugState', async () => {
    const { module, keychainModule } = loadKeychainCommon({
      getGenericPasswordError: new Error(
        'msg: RSA decrypt failed on both current and legacy paths',
      ),
    });
    module.makeSecureKeyChainInstance({ salt: 'salt' });
    const api = module.createBusinessKeychainApi({
      keychainModule: keychainModule as any,
      debugNativeModuleName: DEBUG_MODULE_NAME,
      sourceLabel: 'test',
    });

    const error = await api
      .requestGenericPassword({})
      .catch(caught => caught as Error & Record<string, unknown>);

    expect(module.isBrokenBiometricsEntryError(error)).toBe(true);
    const debugState = (error as Record<string, any>).debugState;
    expect(debugState).toBeTruthy();
    expect(debugState).not.toHaveProperty('storedUsernameBase64');
    expect(debugState).not.toHaveProperty('storedPasswordBase64');
    expect(debugState.hasStoredUsernameBase64).toBe(true);
    expect(debugState.hasStoredPasswordBase64).toBe(true);
    expect(debugState.resolvedCipherStorageName).toBe('KeystoreRSAECB');
  });

  it('passes through unrelated keychain errors without debugState', async () => {
    const { module, keychainModule } = loadKeychainCommon({
      getGenericPasswordError: new Error('msg: some other failure'),
    });
    module.makeSecureKeyChainInstance({ salt: 'salt' });
    const api = module.createBusinessKeychainApi({
      keychainModule: keychainModule as any,
      debugNativeModuleName: DEBUG_MODULE_NAME,
      sourceLabel: 'test',
    });

    const error = await api
      .requestGenericPassword({})
      .catch(caught => caught as Error & Record<string, unknown>);

    expect(module.isBrokenBiometricsEntryError(error)).toBe(false);
    expect((error as Record<string, unknown>).debugState).toBeUndefined();
  });
});
