enableScripts: false

enableTelemetry: 0

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
