import type { UIAuthType } from '@/core/apis/lock';

export function coerceAuthType(
  target: UIAuthType,
  available: UIAuthType[],
): UIAuthType {
  if (!available.length) {
    return 'password';
  }

  return available.includes(target) ? target : available[0] || 'password';
}

export function reconcileAuthTypeSelection(
  current: UIAuthType,
  available: UIAuthType[],
) {
  return available.includes(current)
    ? current
    : coerceAuthType(available[0], available);
}

export function filterAuthTypes(
  authTypes: UIAuthType[],
  context: {
    isBiometricsEnabled: boolean;
    isUseCustomPwd: boolean;
    passwordIsAutoGenerated: boolean;
  },
) {
  const { isBiometricsEnabled, isUseCustomPwd, passwordIsAutoGenerated } =
    context;
  let types = authTypes.filter(type => {
    if (type === 'none') {
      return true;
    }
    if (isUseCustomPwd) {
      if (type === 'biometrics') {
        return isBiometricsEnabled || passwordIsAutoGenerated;
      }
      if (type === 'password') {
        return !passwordIsAutoGenerated;
      }
      return false;
    }

    return false;
  });

  if (types.length === 0) {
    console.warn('No available auth type, fallback to password');
    types =
      isUseCustomPwd && !passwordIsAutoGenerated ? ['password'] : ['none'];
  }

  if (types.length > 1 && types.some(x => x === 'none')) {
    console.warn(
      '`none` authType is not allowed with other types, trimming it.',
    );
    types = types.filter(x => x !== 'none');
  }

  return {
    availableAuthTypes: types,
    disableValidation: (['biometrics', 'password'] as const).every(
      x => !types.includes(x),
    ),
  };
}
