import { filterAuthTypes, reconcileAuthTypeSelection } from './authType';

describe('authentication modal auth type readiness', () => {
  beforeEach(() => {
    jest.spyOn(console, 'warn').mockImplementation(() => undefined);
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('converges from a transient no-auth state after wallet auth is ready', () => {
    const initial = filterAuthTypes(['biometrics', 'password'], {
      isBiometricsEnabled: false,
      isUseCustomPwd: false,
      passwordIsAutoGenerated: false,
    });
    expect(initial.availableAuthTypes).toEqual(['none']);

    const ready = filterAuthTypes(['biometrics', 'password'], {
      isBiometricsEnabled: true,
      isUseCustomPwd: true,
      passwordIsAutoGenerated: true,
    });
    expect(ready.availableAuthTypes).toEqual(['biometrics']);
    expect(reconcileAuthTypeSelection('none', ready.availableAuthTypes)).toBe(
      'biometrics',
    );
  });

  it('preserves an existing valid user selection', () => {
    expect(
      reconcileAuthTypeSelection('password', ['biometrics', 'password']),
    ).toBe('password');
  });

  it('falls back when the selected auth type becomes unavailable', () => {
    expect(reconcileAuthTypeSelection('biometrics', ['password'])).toBe(
      'password',
    );
  });
});
