/* eslint-disable */
// AUTO-GENERATED FROM ./appNavigationGlobals.prod.ts BY `yarn workspace rabby-mobile loadables:generate`.
// DO NOT EDIT THIS FILE DIRECTLY.

export * from './appNavigationGlobals.prod';
