/* eslint-disable */
// AUTO-GENERATED FROM ./homeRootNavigator.prod.ts BY `yarn workspace rabby-mobile loadables:generate`.
// DO NOT EDIT THIS FILE DIRECTLY.

export { HomeScreenNavigator } from '@/screens/Navigators/rootNavigator';
