/* eslint-disable */
// AUTO-GENERATED FROM ./rootNavigatorScreens.prod.ts BY `yarn workspace rabby-mobile loadables:generate`.
// DO NOT EDIT THIS FILE DIRECTLY.

export { default as WebViewControlPreload } from '@/components/WebView/WebViewControlPreload';
