/* eslint-disable */
// AUTO-GENERATED FROM ./singleAddressScreens.lazy.ts BY `yarn workspace rabby-mobile loadables:generate`.
// DO NOT EDIT THIS FILE DIRECTLY.

export * from './singleAddressScreens.lazy';
