/* eslint-disable */
// AUTO-GENERATED EAGER IMPLEMENTATION FROM ./singleAddressScreens.lazy.ts.
// DO NOT EDIT THIS FILE DIRECTLY.

export { default as SingleAddressHomeScreen } from '@/screens/Home/Home';
