import React, { type Ref, useImperativeHandle, useState, useRef } from 'react';
import { AppSwitch2024 } from '@/components/customized/Switch2024';
import { SwitchToggleType } from '@/components';
import { useBiometrics } from '@/hooks/biometrics';
import { useWalletPasswordInfo } from '@/screens/ManagePassword/useManagePassword';
import { AuthenticationModal2024 as AuthenticationModal } from '@/components/AuthenticationModal/AuthenticationModal2024';
import { useTranslation } from 'react-i18next';
import { apisKeychain, apisLock } from '@/core/apis';
import { RequestGenericPurpose } from '@/core/apis/keychain';
import { preferenceService } from '@/core/services';
import SetPasswordBottomSheet from '@/screens/ManagePassword/components/SetPasswordBottomSheet';

function useToggleBiometricsEnabled() {
  const { computed, toggleBiometrics } = useBiometrics();
  const { t } = useTranslation();
  const [sheetVisible, setSheetVisible] = useState(false);
  const [sheetLoading, setSheetLoading] = useState(false);
  const autoGenPasswordRef = useRef('');

  const requestToggleBiometricsEnabled = React.useCallback(
    async (
      nextEnabled: boolean,
      onToggleSuccess?: (enabled: boolean) => void | Promise<void>,
    ) => {
      // When turning OFF and password is auto-generated:
      // verify biometrics → show password setup → update password → turn off
      if (!nextEnabled && preferenceService.store.passwordIsAutoGenerated) {
        try {
          await apisKeychain.requestGenericPassword({
            purpose: RequestGenericPurpose.DECRYPT_PWD,
            onPlainPassword(password) {
              autoGenPasswordRef.current = password;
            },
          });
        } catch (_error) {
          // User cancelled or biometrics failed — abort, switch stays on
          return;
        }

        setSheetVisible(true);
        return;
      }

      // Existing flow (enabling or normal disabling)
      AuthenticationModal.show({
        confirmText: t('global.confirm'),
        cancelText: t('global.cancel'),
        title: nextEnabled
          ? t('component.AuthenticationModals.biometrics.enable', {
              bioType: computed.defaultTypeLabel,
            })
          : t('component.AuthenticationModals.biometrics.disable', {
              bioType: computed.defaultTypeLabel,
            }),
        authType: nextEnabled ? ['password'] : ['none'],
        async onFinished({ getValidatedPassword }) {
          const changed = await toggleBiometrics(nextEnabled, {
            validatedPassword: getValidatedPassword(),
          });
          if (changed) {
            await onToggleSuccess?.(nextEnabled);
          }
        },
      });
    },
    [toggleBiometrics, computed.defaultTypeLabel, t],
  );

  const handleSheetConfirm = React.useCallback(
    async (newPassword: string) => {
      setSheetLoading(true);
      try {
        // 1. Update wallet password from auto-gen to user-chosen
        const result = await apisLock.updateWalletPassword(
          autoGenPasswordRef.current,
          newPassword,
        );
        if (result.error) {
          throw new Error(result.error);
        }

        // 2. Clear the auto-gen flag
        preferenceService.setPasswordIsAutoGenerated(false);

        // 3. Turn off biometrics
        await toggleBiometrics(false, {});
      } catch (_error) {
        // Password update failed — stay on sheet
        return;
      } finally {
        setSheetLoading(false);
      }

      setSheetVisible(false);
    },
    [toggleBiometrics],
  );

  return {
    isBiometricsEnabled: computed.isBiometricsEnabled,
    couldSetupBiometrics: computed.couldSetupBiometrics,
    requestToggleBiometricsEnabled,
    sheetVisible,
    sheetLoading,
    handleSheetConfirm,
    setSheetVisible,
  };
}

export const SwitchBiometricsAuthentication = ({
  ref,
  onToggleSuccess,
  ...props
}: React.ComponentProps<typeof AppSwitch2024> & {
  onToggleSuccess?: (enabled: boolean) => void | Promise<void>;
  ref?: Ref<SwitchToggleType>;
}) => {
  const {
    isBiometricsEnabled,
    couldSetupBiometrics,
    requestToggleBiometricsEnabled,
    sheetVisible,
    sheetLoading,
    handleSheetConfirm,
    setSheetVisible,
  } = useToggleBiometricsEnabled();

  useImperativeHandle(ref, () => ({
    toggle: async (enabled?: boolean) => {
      await requestToggleBiometricsEnabled(
        enabled ?? !isBiometricsEnabled,
        onToggleSuccess,
      );
    },
  }));

  const { hasSetupCustomPassword } = useWalletPasswordInfo();

  return (
    <>
      <AppSwitch2024
        {...props}
        circleSize={20}
        disabled={!hasSetupCustomPassword || !couldSetupBiometrics}
        value={!!isBiometricsEnabled}
        changeValueImmediately={false}
        onValueChange={enabled => {
          requestToggleBiometricsEnabled(enabled, onToggleSuccess);
        }}
      />
      <SetPasswordBottomSheet
        visible={sheetVisible}
        loading={sheetLoading}
        onConfirm={handleSheetConfirm}
        onClose={() => setSheetVisible(false)}
      />
    </>
  );
};
