import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import {
  AppState,
  FlatList,
  ScrollView,
  TouchableOpacity,
  View,
  useWindowDimensions,
} from 'react-native';
import { useIsFocused } from '@react-navigation/native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import QRCode from 'react-native-qrcode-svg';
import RNFS from '@rabby-wallet/react-native-fs';
import { addressUtils } from '@rabby-wallet/base-utils';
import {
  HARDWARE_KEYRING_TYPES,
  KEYRING_CLASS,
  type KeyringAccount,
} from '@rabby-wallet/keyring-utils';

import { RcIconCheckedFilledCC, RcIconUncheckCC } from '@/assets/icons/common';
import NormalScreenContainer from '@/components/ScreenContainer/NormalScreenContainer';
import { AuthenticationModal2024 } from '@/components/AuthenticationModal/AuthenticationModal2024';
import { Text } from '@/components/Typography';
import { Button } from '@/components2024/Button';
import { toast } from '@/components2024/Toast';
import { WalletIcon } from '@/components2024/WalletIcon/WalletIcon';
import {
  BOTTOM_BUTTON_SINGLE_HEIGHT,
  BOTTOM_BUTTON_TITLE_STYLE,
  BOTTOM_BUTTON_TOP_OFFSET,
  getBottomButtonBottomOffset,
} from '@/constant/layout';
import { getSyncTransferDataString } from '@/core/apis/syncExtensionTransfer';
import RNFileHelpers from '@/core/native/RNFileHelpers';
import { keyringServiceApi } from '@/core/serviceApi/keyring';
import { getPasswordIsAutoGeneratedSnapshot } from '@/core/serviceApi/preference';
import { useAccounts } from '@/hooks/account';
import { useTheme2024 } from '@/hooks/theme';
import { createGetStyles2024 } from '@/utils/styles';
import { ensureWalletUnlockedForAction } from '@/utils/walletUnlock';
import { shareLocalFile } from '@/utils/shareLocalFile';
import {
  SYNC_VIDEO_FRAME_DURATION,
  SYNC_VIDEO_TAIL_FRAMES,
  createSyncUREncoder,
} from '@/utils/syncExtensionTransfer';
import { buildSyncVideoFrames } from '@/utils/syncExtensionTransferVideo';
import { useTranslation } from 'react-i18next';

const { ellipsis } = addressUtils;

const QR_REFRESH_INTERVAL_MS = 100;
const VIDEO_SIZE = 1024;
const VIDEO_BIT_RATE = 4_000_000;
const TRANSFER_VIDEO_CACHE_PREFIX = 'rabby-wallet-transfer-sync-export-';
const TRANSFER_VIDEO_CACHE_MAX_AGE_MS = 6 * 60 * 60 * 1000;

async function cleanupStaleTransferVideos(directory: string) {
  try {
    const entries = await RNFS.readDir(directory);
    const staleBefore = Date.now() - TRANSFER_VIDEO_CACHE_MAX_AGE_MS;
    await Promise.all(
      entries
        .filter(entry => {
          const modifiedAt = entry.mtime || entry.ctime;
          return (
            entry.isFile() &&
            entry.name.startsWith(TRANSFER_VIDEO_CACHE_PREFIX) &&
            entry.name.endsWith('.mp4') &&
            modifiedAt instanceof Date &&
            modifiedAt.getTime() < staleBefore
          );
        })
        .map(entry => RNFS.unlink(entry.path).catch(() => undefined)),
    );
  } catch {
    // Cache cleanup is best-effort and must not block a new export.
  }
}

const SYNC_KEYRING_TYPES = new Set<string>([
  KEYRING_CLASS.MNEMONIC,
  KEYRING_CLASS.PRIVATE_KEY,
  KEYRING_CLASS.HARDWARE.ONEKEY,
  KEYRING_CLASS.HARDWARE.LEDGER,
  KEYRING_CLASS.GNOSIS,
  KEYRING_CLASS.HARDWARE.KEYSTONE,
  KEYRING_CLASS.WATCH,
  KEYRING_CLASS.HARDWARE.TREZOR,
]);

type ExportAccount = KeyringAccount & {
  aliasName?: string;
  needPassphrase?: boolean;
  isSlip39?: boolean;
};

type BanReason = 'unsupported' | 'passphrase' | 'slip39' | undefined;

function getAccountKey(account: KeyringAccount) {
  return `${account.type}:${
    account.brandName
  }:${account.address.toLowerCase()}`;
}

function getTypeAddressKey(account: { type: string; address: string }) {
  return `${account.type}:${account.address.toLowerCase()}`;
}

function getBanReason(account: ExportAccount): BanReason {
  if (!SYNC_KEYRING_TYPES.has(account.type)) {
    return 'unsupported';
  }
  if (account.type === KEYRING_CLASS.MNEMONIC) {
    if (account.isSlip39) {
      return 'slip39';
    }
    if (account.needPassphrase) {
      return 'passphrase';
    }
  }
  if (
    account.type === KEYRING_CLASS.HARDWARE.KEYSTONE &&
    account.brandName !== HARDWARE_KEYRING_TYPES.Keystone.brandName
  ) {
    return 'unsupported';
  }
  return undefined;
}

function DynamicTransferQRCode({
  input,
  visible,
  size,
  onReveal,
}: {
  input: string;
  visible: boolean;
  size: number;
  onReveal: () => void;
}) {
  const { t } = useTranslation();
  const encoder = useMemo(() => createSyncUREncoder(input), [input]);
  const [part, setPart] = useState(() => encoder.nextPart());

  useEffect(() => {
    setPart(encoder.nextPart());
    if (!visible) {
      return;
    }

    const timer = setInterval(() => {
      setPart(encoder.nextPart());
    }, QR_REFRESH_INTERVAL_MS);
    return () => clearInterval(timer);
  }, [encoder, visible]);

  return (
    <View style={{ width: size, height: size }}>
      {visible ? (
        <QRCode
          value={part}
          size={size}
          ecl="M"
          quietZone={16}
          backgroundColor="#FFFFFF"
          color="#000000"
        />
      ) : (
        <TouchableOpacity
          activeOpacity={0.8}
          onPress={onReveal}
          style={getHiddenQRCodeStyle(size)}>
          <Text style={hiddenQRCodeTextStyle}>
            {t('page.syncExtensionTransfer.verifyTitle')}
          </Text>
        </TouchableOpacity>
      )}
    </View>
  );
}

function getHiddenQRCodeStyle(size: number) {
  return {
    position: 'absolute' as const,
    left: 0,
    top: 0,
    width: size,
    height: size,
    borderRadius: 12,
    backgroundColor: '#1D1F2C',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  };
}

const hiddenQRCodeTextStyle = {
  color: '#FFFFFF',
  fontSize: 16,
  fontWeight: '600' as const,
};

export default function SyncExtensionExportScreen() {
  const { t } = useTranslation();
  const { styles, colors2024 } = useTheme2024({ getStyle: getStyles });
  const { bottom } = useSafeAreaInsets();
  const { width } = useWindowDimensions();
  const isFocused = useIsFocused();
  const { accounts } = useAccounts();
  const [exportRestrictions, setExportRestrictions] = useState<
    Array<{
      address: string;
      type: string;
      isSlip39: boolean;
      needPassphrase: boolean;
    }>
  >([]);
  const [restrictionsReady, setRestrictionsReady] = useState(false);
  const [selectedKeys, setSelectedKeys] = useState<Set<string>>(
    () => new Set(),
  );
  const [payload, setPayload] = useState('');
  const [isPreparing, setIsPreparing] = useState(false);
  const [videoProgress, setVideoProgress] = useState(0);
  const [appState, setAppState] = useState(AppState.currentState);
  const [qrCodeRevealed, setQRCodeRevealed] = useState(false);
  const payloadJobRef = useRef(0);
  const videoJobRef = useRef(0);
  const nativeVideoJobRef = useRef<string | undefined>(undefined);
  const isMountedRef = useRef(true);
  const isFocusedRef = useRef(isFocused);
  isFocusedRef.current = isFocused;

  useEffect(() => {
    isMountedRef.current = true;
    const subscription = AppState.addEventListener('change', nextState => {
      setAppState(nextState);
      if (nextState !== 'active') {
        setQRCodeRevealed(false);
        payloadJobRef.current += 1;
        videoJobRef.current += 1;
        if (nativeVideoJobRef.current) {
          RNFileHelpers.cancelQRCodeVideoJob(nativeVideoJobRef.current);
          nativeVideoJobRef.current = undefined;
        }
        setIsPreparing(false);
        setVideoProgress(0);
      }
    });
    return () => {
      isMountedRef.current = false;
      payloadJobRef.current += 1;
      videoJobRef.current += 1;
      if (nativeVideoJobRef.current) {
        RNFileHelpers.cancelQRCodeVideoJob(nativeVideoJobRef.current);
        nativeVideoJobRef.current = undefined;
      }
      subscription.remove();
    };
  }, []);

  useEffect(() => {
    if (!isFocused) {
      setQRCodeRevealed(false);
      payloadJobRef.current += 1;
      videoJobRef.current += 1;
      if (nativeVideoJobRef.current) {
        RNFileHelpers.cancelQRCodeVideoJob(nativeVideoJobRef.current);
        nativeVideoJobRef.current = undefined;
      }
      setIsPreparing(false);
      setVideoProgress(0);
    }
  }, [isFocused]);

  useEffect(() => {
    let cancelled = false;
    keyringServiceApi
      .getSyncExportAccountRestrictions()
      .then(restrictions => {
        if (!cancelled) {
          setExportRestrictions(restrictions);
          setRestrictionsReady(true);
        }
      })
      .catch(error => {
        console.error(
          '[SyncExtensionExport] load account restrictions failed',
          error,
        );
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const exportAccounts = useMemo(() => {
    const restrictions = new Map(
      exportRestrictions.map(item => [getTypeAddressKey(item), item]),
    );
    return accounts.map(account => {
      const restriction = restrictions.get(getTypeAddressKey(account));
      return {
        ...account,
        isSlip39: restriction?.isSlip39,
        needPassphrase: account.needPassphrase || restriction?.needPassphrase,
      };
    }) as ExportAccount[];
  }, [accounts, exportRestrictions]);
  const selectableAccounts = useMemo(
    () => exportAccounts.filter(account => !getBanReason(account)),
    [exportAccounts],
  );
  const selectedAccounts = useMemo(
    () =>
      selectableAccounts.filter(account =>
        selectedKeys.has(getAccountKey(account)),
      ),
    [selectableAccounts, selectedKeys],
  );
  const allSelected =
    selectableAccounts.length > 0 &&
    selectedAccounts.length === selectableAccounts.length;
  const qrSize = Math.min(width - 56, 320);
  const qrVisible =
    qrCodeRevealed && isFocused && appState === 'active' && !!payload;

  const toggleAccount = useCallback(
    (account: ExportAccount) => {
      if (!restrictionsReady || isPreparing || getBanReason(account)) {
        return;
      }
      const key = getAccountKey(account);
      setSelectedKeys(previous => {
        const next = new Set(previous);
        if (next.has(key)) {
          next.delete(key);
        } else {
          next.add(key);
        }
        return next;
      });
    },
    [isPreparing, restrictionsReady],
  );

  const toggleAll = useCallback(() => {
    if (!restrictionsReady || isPreparing) {
      return;
    }
    setSelectedKeys(
      allSelected ? new Set() : new Set(selectableAccounts.map(getAccountKey)),
    );
  }, [allSelected, isPreparing, restrictionsReady, selectableAccounts]);

  const createPayload = useCallback(async () => {
    if (
      !isMountedRef.current ||
      !isFocusedRef.current ||
      AppState.currentState !== 'active'
    ) {
      return;
    }
    const job = payloadJobRef.current + 1;
    payloadJobRef.current = job;
    setIsPreparing(true);
    try {
      if (!(await ensureWalletUnlockedForAction())) {
        return;
      }
      const nextPayload = await getSyncTransferDataString(selectedAccounts);
      if (isMountedRef.current && payloadJobRef.current === job) {
        setPayload(nextPayload);
        setQRCodeRevealed(
          isFocusedRef.current && AppState.currentState === 'active',
        );
      }
    } catch (error) {
      if (payloadJobRef.current === job) {
        console.error('[SyncExtensionExport] create payload failed', error);
        toast.error(t('page.syncExtensionTransfer.exportFailed'));
      }
    } finally {
      if (isMountedRef.current && payloadJobRef.current === job) {
        setIsPreparing(false);
      }
    }
  }, [selectedAccounts, t]);

  const handleShowQRCode = useCallback(() => {
    if (!restrictionsReady || !selectedAccounts.length || isPreparing) {
      return;
    }
    if (getPasswordIsAutoGeneratedSnapshot()) {
      toast.error(t('page.syncExtensionTransfer.customPasswordRequired'));
      return;
    }

    AuthenticationModal2024.show({
      title: t('page.syncExtensionTransfer.verifyTitle'),
      description: t('page.syncExtensionTransfer.verifyDescription'),
      hideCancelButton: true,
      onFinished: async () => {
        await createPayload();
      },
    }).catch(error => {
      console.error('[SyncExtensionExport] open auth modal failed', error);
      toast.error(t('page.syncExtensionTransfer.exportFailed'));
    });
  }, [
    createPayload,
    isPreparing,
    restrictionsReady,
    selectedAccounts.length,
    t,
  ]);

  const handleRevealQRCode = useCallback(() => {
    if (!payload || isPreparing) {
      return;
    }
    AuthenticationModal2024.show({
      title: t('page.syncExtensionTransfer.verifyTitle'),
      description: t('page.syncExtensionTransfer.verifyDescription'),
      hideCancelButton: true,
      onFinished: () => {
        if (
          isMountedRef.current &&
          isFocusedRef.current &&
          AppState.currentState === 'active'
        ) {
          setQRCodeRevealed(true);
        }
      },
    }).catch(error => {
      console.error('[SyncExtensionExport] reveal QR code failed', error);
      toast.error(t('page.syncExtensionTransfer.exportFailed'));
    });
  }, [isPreparing, payload, t]);

  const handleDownloadVideo = useCallback(async () => {
    if (!payload || isPreparing) {
      return;
    }

    const job = videoJobRef.current + 1;
    const nativeJobId = `sync-export-${Date.now()}-${job}`;
    videoJobRef.current = job;
    setIsPreparing(true);
    setVideoProgress(0);
    let outputPath = '';

    try {
      const directory =
        RNFS.CachesDirectoryPath ||
        RNFS.TemporaryDirectoryPath ||
        RNFS.DocumentDirectoryPath;
      await cleanupStaleTransferVideos(directory);
      const frames = await buildSyncVideoFrames(payload, {
        isCancelled: () => videoJobRef.current !== job,
        onProgress: progress => {
          if (videoJobRef.current === job) {
            setVideoProgress(Math.round(progress * 50));
          }
        },
      });
      // A cancelled native job may finish cleanup after a replacement starts,
      // so every job needs its own output path.
      outputPath = `${directory}/rabby-wallet-transfer-${nativeJobId}.mp4`;
      nativeVideoJobRef.current = nativeJobId;
      const videoPath = await RNFileHelpers.createQRCodeVideo({
        frames,
        outputPath,
        size: VIDEO_SIZE,
        frameDurationMs: SYNC_VIDEO_FRAME_DURATION,
        bitRate: VIDEO_BIT_RATE,
        tailFrames: SYNC_VIDEO_TAIL_FRAMES,
        jobId: nativeJobId,
      });
      if (nativeVideoJobRef.current === nativeJobId) {
        nativeVideoJobRef.current = undefined;
      }

      if (
        videoJobRef.current !== job ||
        !isFocusedRef.current ||
        AppState.currentState !== 'active'
      ) {
        if (await RNFS.exists(videoPath)) {
          await RNFS.unlink(videoPath).catch(() => undefined);
        }
        return;
      }
      setVideoProgress(100);
      await shareLocalFile({
        path: videoPath,
        name: 'rabby-wallet-transfer.mp4',
        mimeType: 'video/mp4',
        title: t('page.syncExtensionTransfer.downloadVideo'),
        subject: 'rabby-wallet-transfer.mp4',
        cleanupPaths: [videoPath],
        shouldShare: () =>
          videoJobRef.current === job &&
          isFocusedRef.current &&
          AppState.currentState === 'active',
      });
    } catch (error) {
      if (videoJobRef.current === job) {
        console.error('[SyncExtensionExport] create video failed', error);
        toast.error(t('page.syncExtensionTransfer.videoFailed'));
      }
      if (outputPath && (await RNFS.exists(outputPath))) {
        await RNFS.unlink(outputPath).catch(() => undefined);
      }
    } finally {
      if (nativeVideoJobRef.current === nativeJobId) {
        nativeVideoJobRef.current = undefined;
      }
      if (videoJobRef.current === job) {
        setIsPreparing(false);
        setVideoProgress(0);
      }
    }
  }, [isPreparing, payload, t]);

  const editSelection = useCallback(() => {
    payloadJobRef.current += 1;
    videoJobRef.current += 1;
    if (nativeVideoJobRef.current) {
      RNFileHelpers.cancelQRCodeVideoJob(nativeVideoJobRef.current);
      nativeVideoJobRef.current = undefined;
    }
    setPayload('');
    setQRCodeRevealed(false);
    setVideoProgress(0);
    setIsPreparing(false);
  }, []);

  const renderAccount = useCallback(
    ({ item }: { item: ExportAccount }) => {
      const key = getAccountKey(item);
      const banReason = getBanReason(item);
      const selected = !banReason && selectedKeys.has(key);
      const disabledDescription = banReason
        ? t(`page.syncExtensionTransfer.disabled.${banReason}`, {
            type: item.type,
          })
        : '';

      return (
        <TouchableOpacity
          activeOpacity={0.7}
          disabled={!!banReason || !restrictionsReady || isPreparing}
          onPress={() => toggleAccount(item)}
          style={[
            styles.accountItem,
            selected && styles.accountItemSelected,
            (banReason || !restrictionsReady) && styles.accountItemDisabled,
          ]}>
          <WalletIcon
            address={item.address}
            type={item.brandName || item.type}
            width={40}
            height={40}
          />
          <View style={styles.accountInfo}>
            <Text numberOfLines={1} style={styles.accountName}>
              {item.aliasName || ellipsis(item.address, 6)}
            </Text>
            <Text numberOfLines={1} style={styles.accountDescription}>
              {disabledDescription ||
                `${ellipsis(item.address, 5)} · ${item.brandName || item.type}`}
            </Text>
          </View>
          {selected ? (
            <RcIconCheckedFilledCC
              width={22}
              height={22}
              color={colors2024['brand-default']}
            />
          ) : (
            <RcIconUncheckCC
              width={22}
              height={22}
              color={colors2024['neutral-foot']}
            />
          )}
        </TouchableOpacity>
      );
    },
    [
      colors2024,
      isPreparing,
      restrictionsReady,
      selectedKeys,
      styles,
      t,
      toggleAccount,
    ],
  );

  const footerBottom = getBottomButtonBottomOffset(bottom);
  const footerHeight =
    BOTTOM_BUTTON_TOP_OFFSET + BOTTOM_BUTTON_SINGLE_HEIGHT + footerBottom;

  return (
    <NormalScreenContainer overwriteStyle={styles.screen}>
      <View style={styles.container}>
        {payload ? (
          <ScrollView
            showsVerticalScrollIndicator={false}
            contentContainerStyle={[
              styles.qrContent,
              { paddingBottom: footerHeight + 16 },
            ]}>
            <Text style={styles.title}>
              {t('page.syncExtensionTransfer.scanTitle')}
            </Text>
            <Text style={styles.description}>
              {t('page.syncExtensionTransfer.scanDescription')}
            </Text>
            <View style={styles.qrCard}>
              <DynamicTransferQRCode
                input={payload}
                visible={qrVisible}
                size={qrSize}
                onReveal={handleRevealQRCode}
              />
            </View>
            <Text style={styles.selectedCount}>
              {t('page.syncExtensionTransfer.selectedCount', {
                count: selectedAccounts.length,
              })}
            </Text>
            <TouchableOpacity onPress={editSelection}>
              <Text style={styles.editText}>
                {t('page.syncExtensionTransfer.editSelection')}
              </Text>
            </TouchableOpacity>
            <View style={styles.securityTip}>
              <Text style={styles.securityTipText}>
                {t('page.syncExtensionTransfer.securityTip')}
              </Text>
            </View>
          </ScrollView>
        ) : (
          <FlatList
            data={exportAccounts}
            keyExtractor={getAccountKey}
            renderItem={renderAccount}
            extraData={selectedKeys}
            showsVerticalScrollIndicator={false}
            contentContainerStyle={[
              styles.listContent,
              { paddingBottom: footerHeight + 16 },
            ]}
            ListHeaderComponent={
              <View>
                <Text style={styles.title}>
                  {t('page.syncExtensionTransfer.selectTitle')}
                </Text>
                <Text style={styles.description}>
                  {t('page.syncExtensionTransfer.selectDescription')}
                </Text>
                <TouchableOpacity
                  disabled={
                    !restrictionsReady ||
                    isPreparing ||
                    !selectableAccounts.length
                  }
                  onPress={toggleAll}
                  style={styles.selectAllButton}>
                  <Text style={styles.selectAllText}>
                    {t(
                      allSelected
                        ? 'page.syncExtensionTransfer.deselectAll'
                        : 'page.syncExtensionTransfer.selectAll',
                    )}
                  </Text>
                </TouchableOpacity>
              </View>
            }
          />
        )}

        <View
          style={[
            styles.footer,
            {
              height: footerHeight,
              paddingBottom: footerBottom,
            },
          ]}>
          <Button
            height={BOTTOM_BUTTON_SINGLE_HEIGHT}
            titleStyle={BOTTOM_BUTTON_TITLE_STYLE}
            disabled={
              payload
                ? false
                : !restrictionsReady || selectedAccounts.length === 0
            }
            loading={isPreparing}
            showTextOnLoading
            title={
              payload
                ? !qrVisible
                  ? t('page.syncExtensionTransfer.verifyTitle')
                  : isPreparing && videoProgress > 0
                  ? t('page.syncExtensionTransfer.generatingVideo', {
                      progress: videoProgress,
                    })
                  : t('page.syncExtensionTransfer.downloadVideo')
                : t('page.syncExtensionTransfer.showQRCode', {
                    count: selectedAccounts.length,
                  })
            }
            onPress={
              payload
                ? qrVisible
                  ? handleDownloadVideo
                  : handleRevealQRCode
                : handleShowQRCode
            }
          />
        </View>
      </View>
    </NormalScreenContainer>
  );
}

const getStyles = createGetStyles2024(ctx => ({
  screen: {
    flex: 1,
    backgroundColor: ctx.colors2024['neutral-bg-0'],
  },
  container: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  title: {
    color: ctx.colors2024['neutral-title-1'],
    fontFamily: 'SF Pro Rounded',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 24,
    textAlign: 'center',
  },
  description: {
    color: ctx.colors2024['neutral-secondary'],
    fontFamily: 'SF Pro Rounded',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    marginTop: 8,
    marginBottom: 16,
    textAlign: 'center',
  },
  selectAllButton: {
    alignSelf: 'flex-end',
    minHeight: 32,
    justifyContent: 'center',
    marginBottom: 4,
  },
  selectAllText: {
    color: ctx.colors2024['brand-default'],
    fontFamily: 'SF Pro Rounded',
    fontSize: 14,
    fontWeight: '600',
  },
  accountItem: {
    minHeight: 72,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: ctx.colors2024['neutral-card-1'],
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 8,
  },
  accountItemSelected: {
    borderColor: ctx.colors2024['brand-default'],
    backgroundColor: ctx.colors2024['brand-light-1'],
  },
  accountItemDisabled: {
    opacity: 0.45,
  },
  accountInfo: {
    flex: 1,
    minWidth: 0,
  },
  accountName: {
    color: ctx.colors2024['neutral-title-1'],
    fontFamily: 'SF Pro Rounded',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  accountDescription: {
    color: ctx.colors2024['neutral-secondary'],
    fontFamily: 'SF Pro Rounded',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    marginTop: 4,
  },
  qrContent: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  qrCard: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    padding: 8,
    marginTop: 4,
  },
  selectedCount: {
    color: ctx.colors2024['neutral-secondary'],
    fontFamily: 'SF Pro Rounded',
    fontSize: 14,
    lineHeight: 18,
    marginTop: 14,
  },
  editText: {
    color: ctx.colors2024['brand-default'],
    fontFamily: 'SF Pro Rounded',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 8,
  },
  securityTip: {
    borderRadius: 12,
    backgroundColor: ctx.colors2024['orange-light-1'],
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 20,
    width: '100%',
  },
  securityTipText: {
    color: ctx.colors2024['neutral-body'],
    fontFamily: 'SF Pro Rounded',
    fontSize: 12,
    lineHeight: 18,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: BOTTOM_BUTTON_TOP_OFFSET,
    backgroundColor: ctx.colors2024['neutral-bg-0'],
  },
}));
