export function getNextUnlockAuthenticationState({
  usingBiometrics,
  isBiometricsEnabled,
  isBiometricsConfigured,
  passwordIsAutoGenerated,
  couldSetupSystemAuth,
  userSelectedPasswordForSession,
  previousCanUseStoredCredential,
  disableAutoTriggerUnlock = false,
}: {
  usingBiometrics: boolean;
  isBiometricsEnabled: boolean;
  isBiometricsConfigured: boolean;
  passwordIsAutoGenerated: boolean;
  couldSetupSystemAuth: boolean;
  userSelectedPasswordForSession: boolean;
  previousCanUseStoredCredential: boolean;
  disableAutoTriggerUnlock?: boolean;
}) {
  const canUseStoredCredential =
    isBiometricsEnabled || isBiometricsConfigured || passwordIsAutoGenerated;
  const becameAvailable =
    canUseStoredCredential && !previousCanUseStoredCredential;

  if (!canUseStoredCredential) {
    return {
      usingBiometrics: false,
      nextPreviousCanUseStoredCredential: false,
      shouldTriggerAutoUnlock: false,
    };
  }

  if (
    shouldKeepStoredCredentialIconWhenSystemAuthUnavailable({
      isBiometricsEnabled,
      passwordIsAutoGenerated,
      couldSetupSystemAuth,
    })
  ) {
    return {
      usingBiometrics: true,
      nextPreviousCanUseStoredCredential: true,
      shouldTriggerAutoUnlock: false,
    };
  }

  if (userSelectedPasswordForSession) {
    return {
      usingBiometrics,
      nextPreviousCanUseStoredCredential: true,
      shouldTriggerAutoUnlock: false,
    };
  }

  return {
    usingBiometrics: true,
    nextPreviousCanUseStoredCredential: true,
    shouldTriggerAutoUnlock: becameAvailable && !disableAutoTriggerUnlock,
  };
}

export function shouldKeepStoredCredentialIconWhenSystemAuthUnavailable({
  isBiometricsEnabled,
  passwordIsAutoGenerated,
  couldSetupSystemAuth,
}: {
  isBiometricsEnabled: boolean;
  passwordIsAutoGenerated: boolean;
  couldSetupSystemAuth: boolean;
}) {
  return (
    passwordIsAutoGenerated && !isBiometricsEnabled && !couldSetupSystemAuth
  );
}

export function shouldTriggerAutoUnlockFallback({
  isBiometricsEnabled,
  isBiometricsConfigured,
  passwordIsAutoGenerated,
  couldSetupSystemAuth,
  usingPassword,
  userSelectedPasswordForSession,
  disableAutoTriggerUnlock,
}: {
  isBiometricsEnabled: boolean;
  isBiometricsConfigured: boolean;
  passwordIsAutoGenerated: boolean;
  couldSetupSystemAuth: boolean;
  usingPassword: boolean;
  userSelectedPasswordForSession: boolean;
  disableAutoTriggerUnlock: boolean;
}) {
  return (
    !disableAutoTriggerUnlock &&
    !usingPassword &&
    !userSelectedPasswordForSession &&
    (isBiometricsEnabled ||
      isBiometricsConfigured ||
      passwordIsAutoGenerated) &&
    !shouldKeepStoredCredentialIconWhenSystemAuthUnavailable({
      isBiometricsEnabled,
      passwordIsAutoGenerated,
      couldSetupSystemAuth,
    })
  );
}

export function shouldShowSystemAuthUnavailableTipForUnlock({
  biometricsReady,
  isBiometricsEnabled,
  passwordIsAutoGenerated,
  couldSetupSystemAuth,
}: {
  biometricsReady: boolean;
  isBiometricsEnabled: boolean;
  passwordIsAutoGenerated: boolean;
  couldSetupSystemAuth: boolean;
}) {
  return (
    !biometricsReady &&
    shouldKeepStoredCredentialIconWhenSystemAuthUnavailable({
      isBiometricsEnabled,
      passwordIsAutoGenerated,
      couldSetupSystemAuth,
    })
  );
}

export function shouldUsePasswordUnlockMode({
  usingBiometrics,
  isBiometricsEnabled,
  isBiometricsConfigured,
  passwordIsAutoGenerated,
  couldSetupSystemAuth,
}: {
  usingBiometrics: boolean;
  isBiometricsEnabled: boolean;
  isBiometricsConfigured: boolean;
  passwordIsAutoGenerated: boolean;
  couldSetupSystemAuth: boolean;
}) {
  if (
    shouldKeepStoredCredentialIconWhenSystemAuthUnavailable({
      isBiometricsEnabled,
      passwordIsAutoGenerated,
      couldSetupSystemAuth,
    })
  ) {
    return false;
  }

  return (
    !usingBiometrics ||
    (!isBiometricsEnabled &&
      !isBiometricsConfigured &&
      !passwordIsAutoGenerated)
  );
}
