export function getNextUnlockAuthenticationState({
  usingBiometrics,
  isBiometricsEnabled,
  passwordIsAutoGenerated,
  userSelectedPasswordForSession,
  previousCanUseStoredCredential,
  disableAutoTriggerUnlock = false,
}: {
  usingBiometrics: boolean;
  isBiometricsEnabled: boolean;
  passwordIsAutoGenerated: boolean;
  userSelectedPasswordForSession: boolean;
  previousCanUseStoredCredential: boolean;
  disableAutoTriggerUnlock?: boolean;
}) {
  const canUseStoredCredential = isBiometricsEnabled || passwordIsAutoGenerated;
  const becameAvailable =
    canUseStoredCredential && !previousCanUseStoredCredential;

  if (!canUseStoredCredential) {
    return {
      usingBiometrics: false,
      nextPreviousCanUseStoredCredential: false,
      shouldTriggerAutoUnlock: false,
    };
  }

  if (userSelectedPasswordForSession) {
    return {
      usingBiometrics,
      nextPreviousCanUseStoredCredential: true,
      shouldTriggerAutoUnlock: false,
    };
  }

  return {
    usingBiometrics: true,
    nextPreviousCanUseStoredCredential: true,
    shouldTriggerAutoUnlock: becameAvailable && !disableAutoTriggerUnlock,
  };
}
