import { getNextUnlockAuthenticationState } from './authState';

describe('Unlock auth state', () => {
  it('returns to system auth when passcode-capable credentials become available after async biometrics fetch', () => {
    expect(
      getNextUnlockAuthenticationState({
        usingBiometrics: false,
        isBiometricsEnabled: true,
        passwordIsAutoGenerated: false,
        userSelectedPasswordForSession: false,
        previousCanUseStoredCredential: false,
      }),
    ).toEqual({
      usingBiometrics: true,
      nextPreviousCanUseStoredCredential: true,
      shouldTriggerAutoUnlock: true,
    });
  });

  it('keeps password mode when the user already selected password for this unlock session', () => {
    expect(
      getNextUnlockAuthenticationState({
        usingBiometrics: false,
        isBiometricsEnabled: true,
        passwordIsAutoGenerated: false,
        userSelectedPasswordForSession: true,
        previousCanUseStoredCredential: false,
      }),
    ).toEqual({
      usingBiometrics: false,
      nextPreviousCanUseStoredCredential: true,
      shouldTriggerAutoUnlock: false,
    });
  });

  it('switches to password mode when no stored credential unlock path is available', () => {
    expect(
      getNextUnlockAuthenticationState({
        usingBiometrics: true,
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: false,
        userSelectedPasswordForSession: false,
        previousCanUseStoredCredential: true,
      }),
    ).toEqual({
      usingBiometrics: false,
      nextPreviousCanUseStoredCredential: false,
      shouldTriggerAutoUnlock: false,
    });
  });
});
