import * as Sentry from '@sentry/react-native';
import { AppState, Platform, type AppStateStatus } from 'react-native';
import { getBuildNumber, getVersion } from 'react-native-device-info';
import { logger } from '@/utils/logger';
import type { DecryptDiagnosticEvent } from '@/core/utils/encryptorDiagnostics';

export const WALLET_UNLOCK_STALL_THRESHOLD_MS = 20_000;

export type WalletUnlockDiagnosticStage =
  | 'unlock_capability_check'
  | 'keychain_instance_wait'
  | 'keychain_native_get'
  | 'keychain_native_result'
  | 'system_auth_availability'
  | 'system_auth_prompt'
  | 'decrypt_password_payload'
  | 'plain_password_callback'
  | 'submit_password'
  | 'unlock_state_check'
  | 'post_decrypt_keychain_rewrite'
  | 'password_modal'
  | 'ensure_keyring_runtime_ready';

type WalletUnlockDiagnosticData = {
  authenticationType?: number;
  authenticatedByBiometrics?: boolean;
  passwordIsAutoGenerated?: boolean;
  keychainSource?: string;
  storage?: string;
  purpose?: number;
  runtimeReadyReason?: string;
  hasStoredPasswordPayload?: boolean;
  usedFallbackRabbitCode?: boolean;
};

type ActiveWalletUnlockAttempt = {
  id: string;
  startedAt: number;
  stage: WalletUnlockDiagnosticStage;
  stageStartedAt: number;
  stageActiveElapsedMs: number;
  stageActiveSince: number | null;
  stageData: WalletUnlockDiagnosticData;
  attemptData: WalletUnlockDiagnosticData;
  appState: AppStateStatus | null;
  joinedRequestCount: number;
  version: { appVersion?: string; buildVersion?: string };
  reported: boolean;
  timer: ReturnType<typeof setTimeout> | null;
  appStateSubscription: { remove: () => void };
};

let nextAttemptId = 1;
let activeAttempt: ActiveWalletUnlockAttempt | null = null;

export function recordWalletUnlockPayloadDiagnostic(
  attemptId: string | undefined,
  candidateIndex: number,
  candidateCount: number,
  event: DecryptDiagnosticEvent,
) {
  if (!attemptId || activeAttempt?.id !== attemptId) return;
  addUnlockBreadcrumb('wallet_unlock_payload', activeAttempt, {
    candidateIndex,
    candidateCount,
    ...event,
  });
}

function getAppVersionData() {
  try {
    return { appVersion: getVersion(), buildVersion: getBuildNumber() };
  } catch {
    return {};
  }
}

function isAppActive(appState: AppStateStatus | null | undefined) {
  return appState === 'active';
}

function addUnlockBreadcrumb(
  message: string,
  attempt: ActiveWalletUnlockAttempt,
  data: Record<string, unknown> = {},
) {
  const metadata = {
    unlockAttemptId: attempt.id,
    stage: attempt.stage,
    elapsedMs: Date.now() - attempt.startedAt,
    platformVersion: Platform.Version,
    ...attempt.version,
    ...data,
  };
  try {
    // The existing logger policy controls file output; never force logging on.
    logger.info('[wallet-unlock-diagnostic]', { event: message, ...metadata });
  } catch {
    // Diagnostics must not change authentication results.
  }
  try {
    Sentry.addBreadcrumb({
      category: 'wallet.unlock',
      level: 'info',
      message,
      data: metadata,
    });
  } catch {
    // A telemetry failure must not interrupt unlock or attempt cleanup.
  }
}

export function recordWalletUnlockDiagnosticFailure(
  attemptId: string | undefined,
  error: unknown,
) {
  const attempt = activeAttempt;
  if (!attemptId || attempt?.id !== attemptId) {
    return;
  }
  const code =
    error && typeof error === 'object' && 'code' in error
      ? error.code
      : undefined;
  const message = error instanceof Error ? error.message : '';
  const knownCodes = [
    'E_CRYPTO_FAILED',
    'E_KEYSTORE_ACCESS_ERROR',
    'E_KEYSTORE_ACCESS',
    'E_AUTHENTICATION_FAILED',
    'E_USER_CANCELLED',
    'E_BIOMETRIC_CANCELLED',
    'NIL_KEYCHAIN_OBJECT',
    'BROKEN_BIOMETRICS_ENTRY',
    'decrypt_fail',
  ];
  addUnlockBreadcrumb('wallet_unlock_failure', attempt, {
    errorCode:
      typeof code === 'string' && knownCodes.includes(code)
        ? code
        : 'unclassified',
    errorCategory: /bad decrypt|padding|cipher|decrypt/i.test(message)
      ? 'decryption'
      : /keystore|invalidated|key permanently/i.test(message)
      ? 'keystore'
      : /cancel/i.test(message)
      ? 'cancelled'
      : /password/i.test(message)
      ? 'password_or_vault'
      : 'other',
  });
}

function clearAttemptTimer(attempt: ActiveWalletUnlockAttempt) {
  if (attempt.timer) {
    clearTimeout(attempt.timer);
    attempt.timer = null;
  }
}

function updateActiveElapsed(attempt: ActiveWalletUnlockAttempt, now: number) {
  if (attempt.stageActiveSince === null) {
    return;
  }

  attempt.stageActiveElapsedMs += now - attempt.stageActiveSince;
  attempt.stageActiveSince = now;
}

function reportStalledAttempt(attempt: ActiveWalletUnlockAttempt, now: number) {
  if (attempt.reported) {
    return;
  }

  attempt.reported = true;
  try {
    Sentry.captureMessage('wallet_unlock_stalled', {
      level: 'warning',
      fingerprint: ['wallet_unlock_stalled', attempt.stage],
      tags: {
        wallet_unlock_stage: attempt.stage,
        platform: Platform.OS,
      },
      extra: {
        unlockAttemptId: attempt.id,
        currentStage: attempt.stage,
        totalElapsedMs: now - attempt.startedAt,
        stageElapsedMs: now - attempt.stageStartedAt,
        stageActiveElapsedMs: attempt.stageActiveElapsedMs,
        joinedRequestCount: attempt.joinedRequestCount,
        appState: attempt.appState,
        platformVersion: Platform.Version,
        ...attempt.version,
        ...attempt.attemptData,
        ...attempt.stageData,
      },
    });
  } catch {
    // Reporting remains best-effort and at most once per attempt.
  }
}

function scheduleAttemptWatchdog(attempt: ActiveWalletUnlockAttempt) {
  clearAttemptTimer(attempt);
  if (attempt.reported || activeAttempt?.id !== attempt.id) {
    return;
  }

  if (!isAppActive(attempt.appState)) {
    return;
  }

  const now = Date.now();
  updateActiveElapsed(attempt, now);
  const remainingMs = Math.max(
    0,
    WALLET_UNLOCK_STALL_THRESHOLD_MS - attempt.stageActiveElapsedMs,
  );

  attempt.timer = setTimeout(() => {
    attempt.timer = null;
    if (activeAttempt?.id !== attempt.id || attempt.reported) {
      return;
    }

    const checkedAt = Date.now();
    updateActiveElapsed(attempt, checkedAt);
    if (
      isAppActive(attempt.appState) &&
      attempt.stageActiveElapsedMs >= WALLET_UNLOCK_STALL_THRESHOLD_MS
    ) {
      reportStalledAttempt(attempt, checkedAt);
      return;
    }

    scheduleAttemptWatchdog(attempt);
  }, remainingMs);
}

function handleAppStateChange(
  attempt: ActiveWalletUnlockAttempt,
  nextAppState: AppStateStatus,
) {
  if (activeAttempt?.id !== attempt.id) {
    return;
  }

  const now = Date.now();
  updateActiveElapsed(attempt, now);
  attempt.appState = nextAppState;
  attempt.stageActiveSince = isAppActive(nextAppState) ? now : null;
  scheduleAttemptWatchdog(attempt);
}

export function beginWalletUnlockDiagnostics(data: WalletUnlockDiagnosticData) {
  if (activeAttempt) {
    clearAttemptTimer(activeAttempt);
    activeAttempt.appStateSubscription.remove();
  }

  const now = Date.now();
  const attemptId = `wallet-unlock-${now.toString(36)}-${nextAttemptId++}`;
  const attempt = {
    id: attemptId,
    startedAt: now,
    stage: 'unlock_capability_check' as const,
    stageStartedAt: now,
    stageActiveElapsedMs: 0,
    stageActiveSince: isAppActive(AppState.currentState) ? now : null,
    stageData: data,
    attemptData: data,
    appState: AppState.currentState,
    joinedRequestCount: 0,
    version: getAppVersionData(),
    reported: false,
    timer: null,
    appStateSubscription: { remove: () => {} },
  };

  attempt.appStateSubscription = AppState.addEventListener('change', state =>
    handleAppStateChange(attempt, state),
  );
  activeAttempt = attempt;
  addUnlockBreadcrumb('wallet_unlock_started', attempt, {
    stage: attempt.stage,
    ...data,
  });
  scheduleAttemptWatchdog(attempt);

  return attemptId;
}

export function markWalletUnlockDiagnosticStage(
  attemptId: string | undefined,
  stage: WalletUnlockDiagnosticStage,
  data: WalletUnlockDiagnosticData = {},
) {
  const attempt = activeAttempt;
  if (!attemptId || !attempt || attempt.id !== attemptId) {
    return;
  }

  const now = Date.now();
  attempt.stage = stage;
  attempt.stageStartedAt = now;
  attempt.stageActiveElapsedMs = 0;
  attempt.stageActiveSince = isAppActive(attempt.appState) ? now : null;
  attempt.stageData = data;
  addUnlockBreadcrumb('wallet_unlock_stage', attempt, {
    stage,
    ...data,
  });
  scheduleAttemptWatchdog(attempt);
}

export function noteJoinedWalletUnlockRequest(attemptId: string | undefined) {
  const attempt = activeAttempt;
  if (!attemptId || !attempt || attempt.id !== attemptId) {
    return;
  }

  attempt.joinedRequestCount += 1;
  addUnlockBreadcrumb('wallet_unlock_request_joined', attempt, {
    stage: attempt.stage,
    joinedRequestCount: attempt.joinedRequestCount,
  });
}

export function finishWalletUnlockDiagnostics(
  attemptId: string | undefined,
  outcome: 'success' | 'cancelled' | 'error',
) {
  const attempt = activeAttempt;
  if (!attemptId || !attempt || attempt.id !== attemptId) {
    return;
  }

  addUnlockBreadcrumb('wallet_unlock_finished', attempt, {
    outcome,
    stage: attempt.stage,
    totalElapsedMs: Date.now() - attempt.startedAt,
  });
  clearAttemptTimer(attempt);
  attempt.appStateSubscription.remove();
  activeAttempt = null;
}
