describe('utils/walletUnlock', () => {
  const setup = async ({
    isUnlocked = false,
    passwordIsAutoGenerated = false,
    isAuthenticatedByBiometrics = true,
    supportedBiometryType = 'Fingerprint' as string | null,
    rejectKeychainRequest = false,
    isAndroid = true,
  } = {}) => {
    jest.resetModules();

    jest.spyOn(console, 'error').mockImplementation(() => {});

    const mockHideUnlockingToast = jest.fn();
    const mockToastUnlocking = jest.fn(() => mockHideUnlockingToast);
    const mockVerifyPasswordOrUnlock = jest.fn(async () => undefined);
    const mockRequestGenericPassword = jest.fn(async options => {
      if (rejectKeychainRequest) {
        throw new Error('Keychain unavailable');
      }

      await options.onPlainPassword?.('plain-password');
      return { actionSuccess: true };
    });
    const mockGetSupportedBiometryType = jest.fn(
      async () => supportedBiometryType,
    );
    const mockShowAuthenticationModal = jest.fn(async config => {
      config.onFinished?.();
      return { hideModal: jest.fn() };
    });

    jest.doMock('@/core/apis/keychain', () => ({
      RequestGenericPurpose: {
        DECRYPT_PWD: 11,
      },
      isAuthenticatedByBiometrics: jest.fn(() => isAuthenticatedByBiometrics),
      getSupportedBiometryType: mockGetSupportedBiometryType,
      requestGenericPassword: mockRequestGenericPassword,
    }));

    jest.doMock('@/core/native/utils', () => ({
      IS_ANDROID: isAndroid,
      IS_IOS: !isAndroid,
    }));

    jest.doMock('@/core/apis/lock', () => ({
      isUnlocked: jest.fn(() => isUnlocked),
      verifyPasswordOrUnlock: mockVerifyPasswordOrUnlock,
    }));

    jest.doMock('@/core/services', () => ({
      preferenceService: {
        store: {
          passwordIsAutoGenerated,
        },
      },
    }));

    jest.doMock('@/utils/toastUnlocking', () => ({
      toastUnlocking: mockToastUnlocking,
    }));

    jest.doMock('@/utils/walletUnlockGuard', () => ({
      setWalletUnlockRequester: jest.fn(),
    }));

    jest.doMock(
      '@/components/AuthenticationModal/AuthenticationModal2024',
      () => ({
        AuthenticationModal2024: {
          show: mockShowAuthenticationModal,
        },
      }),
    );

    const walletUnlock =
      require('./walletUnlock') as typeof import('./walletUnlock');

    return {
      walletUnlock,
      mockVerifyPasswordOrUnlock,
      mockRequestGenericPassword,
      mockGetSupportedBiometryType,
      mockShowAuthenticationModal,
      mockToastUnlocking,
      mockHideUnlockingToast,
    };
  };

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('uses system credential unlock for autogenerated passwords even when no biometry type is supported', async () => {
    const {
      walletUnlock,
      mockVerifyPasswordOrUnlock,
      mockRequestGenericPassword,
      mockGetSupportedBiometryType,
      mockShowAuthenticationModal,
      mockToastUnlocking,
      mockHideUnlockingToast,
    } = await setup({
      passwordIsAutoGenerated: true,
      supportedBiometryType: null,
    });

    await walletUnlock.ensureWalletUnlocked();

    expect(mockGetSupportedBiometryType).not.toHaveBeenCalled();
    expect(mockRequestGenericPassword).toHaveBeenCalledWith(
      expect.objectContaining({
        purpose: 11,
      }),
    );
    expect(mockVerifyPasswordOrUnlock).toHaveBeenCalledWith('plain-password');
    expect(mockShowAuthenticationModal).not.toHaveBeenCalled();
    expect(mockToastUnlocking).toHaveBeenCalledTimes(1);
    expect(mockHideUnlockingToast).toHaveBeenCalledTimes(1);
  });

  it('shows unlocking toast for biometric post-unlock', async () => {
    const {
      walletUnlock,
      mockRequestGenericPassword,
      mockToastUnlocking,
      mockHideUnlockingToast,
      mockShowAuthenticationModal,
    } = await setup();

    await walletUnlock.ensureWalletUnlocked();

    expect(mockToastUnlocking.mock.invocationCallOrder[0]).toBeLessThan(
      mockRequestGenericPassword.mock.invocationCallOrder[0],
    );
    expect(mockToastUnlocking).toHaveBeenCalledTimes(1);
    expect(mockHideUnlockingToast).toHaveBeenCalledTimes(1);
    expect(mockShowAuthenticationModal).not.toHaveBeenCalled();
  });

  it('shows unlocking toast for non-Android biometric post-unlock', async () => {
    const { walletUnlock, mockToastUnlocking, mockHideUnlockingToast } =
      await setup({ isAndroid: false });

    await walletUnlock.ensureWalletUnlocked();

    expect(mockToastUnlocking).toHaveBeenCalledTimes(1);
    expect(mockHideUnlockingToast).toHaveBeenCalledTimes(1);
  });

  it('shows unlocking toast for FaceID-style biometry', async () => {
    const { walletUnlock, mockToastUnlocking, mockHideUnlockingToast } =
      await setup({ supportedBiometryType: 'FaceID' });

    await walletUnlock.ensureWalletUnlocked();

    expect(mockToastUnlocking).toHaveBeenCalledTimes(1);
    expect(mockHideUnlockingToast).toHaveBeenCalledTimes(1);
  });

  it('does not fall back to password modal when autogenerated-password keychain unlock fails', async () => {
    const {
      walletUnlock,
      mockShowAuthenticationModal,
      mockToastUnlocking,
      mockHideUnlockingToast,
    } = await setup({
      passwordIsAutoGenerated: true,
      rejectKeychainRequest: true,
    });

    await expect(walletUnlock.ensureWalletUnlocked()).rejects.toMatchObject({
      name: 'WalletUnlockCancelledError',
    });
    expect(mockShowAuthenticationModal).not.toHaveBeenCalled();
    expect(mockToastUnlocking).toHaveBeenCalledTimes(1);
    expect(mockHideUnlockingToast).toHaveBeenCalledTimes(1);
  });
});
