describe('utils/walletUnlockDiagnostics', () => {
  const setup = () => {
    jest.resetModules();
    jest.useFakeTimers();
    jest.setSystemTime(new Date('2026-08-13T00:00:00.000Z'));

    let currentAppState = 'active';
    const appStateListeners = new Set<(state: string) => void>();
    const mockRemoveAppStateListener = jest.fn();
    const mockCaptureMessage = jest.fn();
    const mockAddBreadcrumb = jest.fn();

    jest.doMock('react-native', () => ({
      AppState: {
        get currentState() {
          return currentAppState;
        },
        addEventListener: jest.fn(
          (_event: string, listener: (state: string) => void) => {
            appStateListeners.add(listener);
            return {
              remove: () => {
                appStateListeners.delete(listener);
                mockRemoveAppStateListener();
              },
            };
          },
        ),
      },
      Platform: {
        OS: 'android',
        Version: 27,
      },
    }));
    jest.doMock('@sentry/react-native', () => ({
      addBreadcrumb: mockAddBreadcrumb,
      captureMessage: mockCaptureMessage,
    }));

    const diagnostics =
      require('./walletUnlockDiagnostics') as typeof import('./walletUnlockDiagnostics');

    return {
      diagnostics,
      mockCaptureMessage,
      mockAddBreadcrumb,
      mockRemoveAppStateListener,
      setAppState(nextState: string) {
        currentAppState = nextState;
        appStateListeners.forEach(listener => listener(nextState));
      },
    };
  };

  afterEach(() => {
    jest.clearAllTimers();
    jest.useRealTimers();
    jest.restoreAllMocks();
  });

  it('reports one production-safe event after a stage is active for 20 seconds', () => {
    const { diagnostics, mockCaptureMessage } = setup();
    const attemptId = diagnostics.beginWalletUnlockDiagnostics({
      authenticationType: 1,
      authenticatedByBiometrics: true,
      passwordIsAutoGenerated: false,
    });

    diagnostics.markWalletUnlockDiagnosticStage(
      attemptId,
      'system_auth_prompt',
      {
        keychainSource: '9.0.0',
        storage: 'KeystoreAESGCM_NoAuth',
      },
    );
    diagnostics.noteJoinedWalletUnlockRequest(attemptId);
    jest.advanceTimersByTime(diagnostics.WALLET_UNLOCK_STALL_THRESHOLD_MS);

    expect(mockCaptureMessage).toHaveBeenCalledTimes(1);
    expect(mockCaptureMessage).toHaveBeenCalledWith(
      'wallet_unlock_stalled',
      expect.objectContaining({
        fingerprint: ['wallet_unlock_stalled', 'system_auth_prompt'],
        tags: expect.objectContaining({
          wallet_unlock_stage: 'system_auth_prompt',
        }),
        extra: expect.objectContaining({
          unlockAttemptId: attemptId,
          currentStage: 'system_auth_prompt',
          stageActiveElapsedMs: 20_000,
          joinedRequestCount: 1,
          authenticationType: 1,
          authenticatedByBiometrics: true,
          passwordIsAutoGenerated: false,
          keychainSource: '9.0.0',
          storage: 'KeystoreAESGCM_NoAuth',
          platformVersion: 27,
        }),
      }),
    );

    jest.advanceTimersByTime(60_000);
    expect(mockCaptureMessage).toHaveBeenCalledTimes(1);
  });

  it('resets the stall window when the unlock stage progresses', () => {
    const { diagnostics, mockCaptureMessage } = setup();
    const attemptId = diagnostics.beginWalletUnlockDiagnostics({});

    jest.advanceTimersByTime(19_000);
    diagnostics.markWalletUnlockDiagnosticStage(attemptId, 'submit_password');
    jest.advanceTimersByTime(1_000);
    expect(mockCaptureMessage).not.toHaveBeenCalled();

    jest.advanceTimersByTime(19_000);
    expect(mockCaptureMessage).toHaveBeenCalledTimes(1);
    expect(mockCaptureMessage).toHaveBeenCalledWith(
      'wallet_unlock_stalled',
      expect.objectContaining({
        tags: expect.objectContaining({
          wallet_unlock_stage: 'submit_password',
        }),
      }),
    );
  });

  it('does not count time spent in the background as an active stall', () => {
    const { diagnostics, mockCaptureMessage, setAppState } = setup();
    diagnostics.beginWalletUnlockDiagnostics({});

    jest.advanceTimersByTime(10_000);
    setAppState('background');
    jest.advanceTimersByTime(60_000);
    expect(mockCaptureMessage).not.toHaveBeenCalled();

    setAppState('active');
    jest.advanceTimersByTime(9_999);
    expect(mockCaptureMessage).not.toHaveBeenCalled();
    jest.advanceTimersByTime(1);
    expect(mockCaptureMessage).toHaveBeenCalledTimes(1);
  });

  it('cleans up without reporting after the attempt finishes', () => {
    const { diagnostics, mockCaptureMessage, mockRemoveAppStateListener } =
      setup();
    const attemptId = diagnostics.beginWalletUnlockDiagnostics({});

    diagnostics.finishWalletUnlockDiagnostics(attemptId, 'success');
    jest.advanceTimersByTime(60_000);

    expect(mockCaptureMessage).not.toHaveBeenCalled();
    expect(mockRemoveAppStateListener).toHaveBeenCalledTimes(1);
  });
});
