# 不要 .so 中的 build_id
# 这会确保我们的链接器标志有最高优先级
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--build-id=none" CACHE STRING "Force linker flags for reproducible builds" FORCE)

# 某些三方 native 模块会把 __FILE__ 这类源码路径编进 .so。
# HASH_CHECK worktree 在不同机器上的真实路径不同，所以编译期统一映射到固定前缀。
set(_RABBY_HASHCHECK_CANONICAL_ROOT "/__rabby_android_hashcheck__")
set(_RABBY_HASHCHECK_PREFIX_FLAGS "")

foreach(_RABBY_HASHCHECK_WORK_DIR
    "$ENV{RABBY_MOBILE_HASHCHECK_WORK_DIR}"
    "$ENV{RABBY_MOBILE_HASHCHECK_WORK_DIR_ALT}"
)
  if(_RABBY_HASHCHECK_WORK_DIR)
    file(TO_CMAKE_PATH "${_RABBY_HASHCHECK_WORK_DIR}" _RABBY_HASHCHECK_WORK_DIR)
    list(APPEND _RABBY_HASHCHECK_PREFIX_FLAGS
      "-fdebug-prefix-map=${_RABBY_HASHCHECK_WORK_DIR}=${_RABBY_HASHCHECK_CANONICAL_ROOT}"
      "-ffile-prefix-map=${_RABBY_HASHCHECK_WORK_DIR}=${_RABBY_HASHCHECK_CANONICAL_ROOT}"
      "-fmacro-prefix-map=${_RABBY_HASHCHECK_WORK_DIR}=${_RABBY_HASHCHECK_CANONICAL_ROOT}"
    )
  endif()
endforeach()

list(REMOVE_DUPLICATES _RABBY_HASHCHECK_PREFIX_FLAGS)

if(_RABBY_HASHCHECK_PREFIX_FLAGS)
  string(JOIN " " _RABBY_HASHCHECK_PREFIX_FLAGS_STRING ${_RABBY_HASHCHECK_PREFIX_FLAGS})
  foreach(_RABBY_HASHCHECK_FLAG_VAR
      CMAKE_C_FLAGS
      CMAKE_CXX_FLAGS
      CMAKE_C_FLAGS_RELEASE
      CMAKE_CXX_FLAGS_RELEASE
      CMAKE_C_FLAGS_RELWITHDEBINFO
      CMAKE_CXX_FLAGS_RELWITHDEBINFO
  )
    set(${_RABBY_HASHCHECK_FLAG_VAR} "${${_RABBY_HASHCHECK_FLAG_VAR}} ${_RABBY_HASHCHECK_PREFIX_FLAGS_STRING}" CACHE STRING "Android HASH_CHECK prefix-map flags" FORCE)
  endforeach()
endif()
