import {
  decryptFiles,
  detectCloudIsAvailable,
  getBackupsFromCloud,
  saveMnemonicToCloud,
} from '@/core/utils/cloudBackup';
import React, { useMemo } from 'react';
import { View } from 'react-native';
import { BackupUnlockScreen } from './BackupUnlockScreen';
import { toast } from '@/components2024/Toast';
import { useTranslation } from 'react-i18next';
import { addKeyringAndactiveAndPersistAccounts } from '@/core/apis/mnemonic';
import { keyringService, preferenceService } from '@/core/services';
import { replaceToFirst } from '@/utils/navigation';
import { RootNames } from '@/constant/layout';
import { KEYRING_CLASS, KEYRING_TYPE } from '@rabby-wallet/keyring-utils';
import { IS_IOS } from '@/core/native/utils';
import { useCreateAddressProc } from '@/hooks/address/useNewUser';
import { apisLock } from '@/core/apis';
import { storeApisBiometrics } from '@/hooks/biometrics';
import SetPasswordBottomSheet from '@/screens/ManagePassword/components/SetPasswordBottomSheet';

interface Props {
  onDone: () => void;
  delaySetPassword?: boolean;
  /** Seed phrase for existing user backup (from authentication) */
  seedPhraseData?: string;
  /** Skip keyring creation after backup (for existing user flow) */
  skipKeyringCreation?: boolean;
  /** Auto-generated password from biometric verification. When provided and password is auto-generated,
   * SetPasswordBottomSheet is shown instead of BackupUnlockScreen. */
  autoGeneratedPassword?: string;
}

export const SeedPhraseBackupToCloud: React.FC<Props> = ({
  onDone,
  delaySetPassword,
  seedPhraseData: externalSeedPhrase,
  skipKeyringCreation = false,
  autoGeneratedPassword,
}) => {
  const passwordIsAutoGenerated =
    !!autoGeneratedPassword && preferenceService.store.passwordIsAutoGenerated;
  const createAddressProc = useCreateAddressProc();

  const { seedPharseData, addressList, confirmPassword } = createAddressProc;

  const isExistingUserBackup = externalSeedPhrase !== undefined;

  const {
    seedPhrase,
    alias,
    address,
    accountsToCreate = [],
  } = useMemo(() => {
    // For existing user backup, use the provided seed phrase
    if (isExistingUserBackup) {
      return {
        seedPhrase: externalSeedPhrase,
        alias: '',
        address: '',
        accountsToCreate: [] as never[],
      };
    }
    // For new user flow, use data from createAddressProc
    return {
      seedPhrase: seedPharseData,
      alias: addressList?.[0]?.aliasName || '',
      address: addressList?.[0]?.address || '',
      accountsToCreate: addressList || [],
    };
  }, [externalSeedPhrase, isExistingUserBackup, seedPharseData, addressList]);

  const { t } = useTranslation();

  const handleUpload = React.useCallback(
    async (password: string) => {
      if (!password) {
        toast.show('must have password');
        return;
      }

      try {
        if (!isExistingUserBackup && delaySetPassword) {
          const res = await confirmPassword();
          if (!res) {
            return; // error set password
          }
        }

        const filename = await saveMnemonicToCloud({
          mnemonic: seedPhrase,
          password,
        });
        // check if the mnemonic is uploaded successfully
        const files = await getBackupsFromCloud([filename]);
        await decryptFiles({ password, files });
        toast.success(
          IS_IOS
            ? t('page.newAddress.seedPhrase.backupSuccessICloud')
            : t('page.newAddress.seedPhrase.backupSuccessGDrive'),
        );

        onDone();

        // Only create keyring for new user flow (not for existing user backup)
        if (
          !isExistingUserBackup &&
          !skipKeyringCreation &&
          !delaySetPassword
        ) {
          const mnemonics = seedPhrase;
          const passphrase = '';
          await addKeyringAndactiveAndPersistAccounts(
            mnemonics,
            passphrase,
            accountsToCreate,
            true,
          );
          keyringService.removePreMnemonics();
          replaceToFirst(RootNames.StackAddress, {
            screen: RootNames.ImportSuccess2024,
            params: {
              type: KEYRING_TYPE.HdKeyring,
              brandName: KEYRING_CLASS.MNEMONIC,
              isFirstImport: true,
              isFirstCreate: true,
              address: [address],
              mnemonics,
              passphrase,
              isExistedKR: false,
              alias,
            },
          });
        }
      } catch (e) {
        toast.error(t('page.newAddress.seedPhrase.backupFailedTitle'));
      }
    },
    [
      onDone,
      t,
      seedPhrase,
      address,
      alias,
      accountsToCreate,
      confirmPassword,
      isExistingUserBackup,
      skipKeyringCreation,
      delaySetPassword,
    ],
  );

  const [showSetPasswordSheet, setShowSetPasswordSheet] = React.useState(true);
  const [setPasswordLoading, setSetPasswordLoading] = React.useState(false);

  const handleSetPasswordAndUpload = React.useCallback(
    async (newPassword: string) => {
      setSetPasswordLoading(true);
      try {
        await apisLock.updateWalletPassword(
          autoGeneratedPassword!,
          newPassword,
        );
        preferenceService.setPasswordIsAutoGenerated(false);
        await storeApisBiometrics.toggleBiometrics(true, {
          validatedPassword: newPassword,
        });
        await handleUpload(newPassword);
      } catch {
        // Stay on sheet on failure
      } finally {
        setSetPasswordLoading(false);
        setShowSetPasswordSheet(false);
      }
    },
    [autoGeneratedPassword, handleUpload],
  );

  React.useEffect(() => {
    detectCloudIsAvailable().then(isAvailable => {
      if (!isAvailable) {
        toast.error(
          t('page.newAddress.seedPhrase.backupErrorCloudNotAvailable'),
        );
        onDone();
      }
    });
  }, [onDone, t]);

  if (passwordIsAutoGenerated) {
    return (
      <SetPasswordBottomSheet
        visible={showSetPasswordSheet}
        loading={setPasswordLoading}
        onConfirm={handleSetPasswordAndUpload}
        onClose={onDone}
      />
    );
  }

  return (
    <View>
      <BackupUnlockScreen onConfirm={handleUpload} />
    </View>
  );
};
