export enum HistoryItemCateType {
  Send = 'send',
  Approve = 'approve',
  Recieve = 'receive',
  Revoke = 'revoke',
  Bridge = 'bridge',
  Swap = 'swap',
  Contract = 'contract',
  UnKnown = 'interaction',
  Cancel = 'cancel',
  Buy = 'buy',
  GAS_DEPOSIT = 'gas_deposit',
  GAS_WITHDRAW = 'gas_withdraw',
  GAS_RECEIVED = 'gas_received',
}
