import React from 'react';
import { act, render } from '@testing-library/react-native';
import AuthButton from './index';
import { Button } from '../Button';
import { useAuthFormGuard } from '@/hooks/useAuthFormGuard';

type AuthCallbacks = {
  onFinished: () => void;
  onCancel: () => void;
  onDismiss: () => void;
};
const mockShow = jest.fn();
const mockRequestPassword = jest.fn();
let mockBiometricsEnabled = false;
let mockAutoPassword = false;

jest.mock('@/hooks/theme', () => ({
  useTheme2024: () => ({ styles: {}, colors2024: {} }),
}));
jest.mock('@/utils/styles', () => ({
  createGetStyles2024: (fn: unknown) => fn,
}));
jest.mock('@/hooks/biometrics', () => ({
  useBiometrics: () => ({
    computed: { isBiometricsEnabled: mockBiometricsEnabled },
  }),
}));
jest.mock('@/core/apis', () => ({
  apisKeychain: {
    requestGenericPassword: (...args: unknown[]) =>
      mockRequestPassword(...args),
  },
  apisLock: { verifyPasswordOrUnlock: jest.fn() },
}));
jest.mock('@/core/apis/keychain', () => ({
  RequestGenericPurpose: { DECRYPT_PWD: 'decrypt' },
}));
jest.mock('@/core/serviceApi/preference', () => ({
  getPasswordIsAutoGeneratedSnapshot: () => mockAutoPassword,
}));
jest.mock('@/core/apis/lock', () => ({ updateUnlockTime: jest.fn() }));
jest.mock('@/components/AuthenticationModal/AuthenticationModal2024', () => ({
  AuthenticationModal2024: { show: (...args: unknown[]) => mockShow(...args) },
}));
jest.mock('react-i18next', () => ({
  useTranslation: () => ({ t: (key: string) => key }),
}));
jest.mock('../Button', () => ({ Button: 'Button' }));

describe('AuthButton attempt lifetime (component unit)', () => {
  beforeEach(() => {
    mockShow.mockReset();
    mockRequestPassword.mockReset();
    mockBiometricsEnabled = false;
    mockAutoPassword = false;
    jest.spyOn(console, 'error').mockImplementation(() => {});
  });
  afterEach(() => jest.restoreAllMocks());

  it('ignores cancelled attempt A after retry B, even when the form is unchanged', async () => {
    const submit = jest.fn();
    function Form() {
      const guard = useAuthFormGuard({ amount: '1' }, jest.fn());
      return (
        <AuthButton
          onBeforeAuth={guard.onBeforeAuth}
          onCancel={guard.onCancel}
          onAuthModalDismiss={guard.onAuthModalDismiss}
          onFinished={() => guard.onFinished(submit)}
        />
      );
    }
    const view = render(<Form />);
    await act(async () => {
      await view.UNSAFE_getByType(Button).props.onPress();
    });
    const attemptA = mockShow.mock.calls[0][0] as AuthCallbacks;
    act(() => {
      attemptA.onCancel();
      attemptA.onDismiss();
    });
    await act(async () => {
      await view.UNSAFE_getByType(Button).props.onPress();
    });
    const attemptB = mockShow.mock.calls[1][0] as AuthCallbacks;
    await act(async () => {
      attemptA.onFinished();
    });
    expect(submit).not.toHaveBeenCalled();
    await act(async () => {
      attemptB.onDismiss();
      attemptB.onFinished();
    });
    expect(submit).toHaveBeenCalledTimes(1);
  });

  it('keeps single-flight until dismissal, then accepts success only once', async () => {
    const onFinished = jest.fn();
    const onAuthModalDismiss = jest.fn();
    const view = render(
      <AuthButton
        onFinished={onFinished}
        onAuthModalDismiss={onAuthModalDismiss}
      />,
    );
    const press = () => view.UNSAFE_getByType(Button).props.onPress();
    await act(async () => {
      await press();
      await press();
    });
    expect(mockShow).toHaveBeenCalledTimes(1);
    const attempt = mockShow.mock.calls[0][0] as AuthCallbacks;
    act(() => {
      attempt.onDismiss();
      attempt.onFinished();
      attempt.onFinished();
    });
    expect(onAuthModalDismiss).toHaveBeenCalledTimes(1);
    expect(onFinished).toHaveBeenCalledTimes(1);
  });

  it('ignores stale cancellation and dismissal after a new attempt starts', async () => {
    const onCancel = jest.fn();
    const onAuthModalDismiss = jest.fn();
    const view = render(
      <AuthButton
        onCancel={onCancel}
        onAuthModalDismiss={onAuthModalDismiss}
      />,
    );
    const press = () => view.UNSAFE_getByType(Button).props.onPress();
    await act(async () => {
      await press();
    });
    const first = mockShow.mock.calls[0][0] as AuthCallbacks;
    act(() => first.onCancel());
    await act(async () => {
      await press();
    });
    act(() => {
      first.onCancel();
      first.onDismiss();
    });
    await act(async () => {
      await press();
    });
    expect(mockShow).toHaveBeenCalledTimes(2);
    expect(onCancel).toHaveBeenCalledTimes(1);
    expect(onAuthModalDismiss).not.toHaveBeenCalled();
  });

  it('releases single-flight when pre-auth preparation throws', async () => {
    const onBeforeAuth = jest.fn().mockImplementationOnce(() => {
      throw new Error('prepare failed');
    });
    const onCancel = jest.fn();
    const view = render(
      <AuthButton onBeforeAuth={onBeforeAuth} onCancel={onCancel} />,
    );
    const press = () => view.UNSAFE_getByType(Button).props.onPress();
    await act(async () => {
      await press();
      await press();
    });
    expect(onBeforeAuth).toHaveBeenCalledTimes(2);
    expect(onCancel).toHaveBeenCalledTimes(1);
    expect(mockShow).toHaveBeenCalledTimes(1);
  });

  it('releases single-flight after a modal presentation rejection', async () => {
    mockShow.mockRejectedValueOnce(new Error('presentation failed'));
    const onCancel = jest.fn();
    const view = render(<AuthButton onCancel={onCancel} />);
    const press = () => view.UNSAFE_getByType(Button).props.onPress();
    await act(async () => {
      await press();
      await press();
    });
    expect(onCancel).toHaveBeenCalledTimes(1);
    expect(mockShow).toHaveBeenCalledTimes(2);
  });

  it('cancels a failed generated-password auth and allows retry', async () => {
    mockAutoPassword = true;
    mockRequestPassword.mockRejectedValue(new Error('cancelled'));
    const onCancel = jest.fn();
    const view = render(<AuthButton onCancel={onCancel} />);
    const press = () => view.UNSAFE_getByType(Button).props.onPress();
    await act(async () => {
      await press();
      await press();
    });
    expect(onCancel).toHaveBeenCalledTimes(2);
    expect(mockShow).not.toHaveBeenCalled();
  });

  it('does not reopen password auth if a biometric success consumer throws', async () => {
    mockBiometricsEnabled = true;
    mockRequestPassword.mockImplementation(async ({ onPlainPassword }) => {
      await onPlainPassword('test-only-password');
    });
    const onFinished = jest.fn(() => {
      throw new Error('consumer failed');
    });
    const view = render(<AuthButton onFinished={onFinished} />);
    const press = () => view.UNSAFE_getByType(Button).props.onPress();
    await act(async () => {
      await press();
      await press();
    });
    expect(onFinished).toHaveBeenCalledTimes(2);
    expect(mockShow).not.toHaveBeenCalled();
  });
});
