import { useTheme2024 } from '@/hooks/theme';
import { createGetStyles2024 } from '@/utils/styles';
import { useCallback, useRef } from 'react';
import { useBiometrics } from '@/hooks/biometrics';
import { apisKeychain, apisLock } from '@/core/apis';
import { getPasswordIsAutoGeneratedSnapshot } from '@/core/serviceApi/preference';
import { RequestGenericPurpose } from '@/core/apis/keychain';
import { AuthenticationModal2024 } from '@/components/AuthenticationModal/AuthenticationModal2024';
import { useTranslation } from 'react-i18next';
import type { ButtonProps } from '../Button';
import { Button } from '../Button';
import RcIconLock from '@/assets2024/icons/common/lock-cc.svg';
import RcIconKeychainFaceIdCC from '@/assets2024/icons/common/fack_id.svg';
import RcIconKeychainFingerprintCC from '@/assets2024/icons/common/fingerprint.svg';
import { updateUnlockTime } from '@/core/apis/lock';

export type IAuthButtonProps = Omit<ButtonProps, 'onPress'> & {
  onFinished?: () => void;
  onCancel?: () => void;
  onAuthModalDismiss?: () => void;
  onBeforeAuth?: () => void;
  authTitle?: string;
  syncUnlockTime?: boolean;
  iconColor?: string;
};

const AuthButton: React.FC<IAuthButtonProps> = ({
  onFinished: _onFinished,
  onBeforeAuth,
  onCancel,
  onAuthModalDismiss,
  authTitle,
  syncUnlockTime,
  iconColor,
  ...props
}) => {
  const { styles, colors2024 } = useTheme2024({ getStyle });
  const { t } = useTranslation();
  const {
    computed: { isBiometricsEnabled, isFaceID, isUsingDevicePasscode },
  } = useBiometrics({ autoFetch: true });

  const isProcessingRef = useRef(false);
  const authAttemptRef = useRef(0);

  const onFinished = useCallback(() => {
    if (syncUnlockTime) {
      updateUnlockTime();
    }
    _onFinished?.();
  }, [syncUnlockTime, _onFinished]);

  const validationHandler = password => {
    return apisLock.verifyPasswordOrUnlock(password);
  };
  const unlockWithBiometrics = useCallback(async () => {
    if (isProcessingRef.current) {
      return;
    }
    isProcessingRef.current = true;
    const attempt = ++authAttemptRef.current;
    let settled = false;
    const isCurrentAttempt = () =>
      authAttemptRef.current === attempt && !settled;

    const finish = () => {
      if (!isCurrentAttempt()) {
        return;
      }
      settled = true;
      isProcessingRef.current = false;
      onFinished?.();
    };

    const cancel = () => {
      if (!isCurrentAttempt()) {
        return;
      }
      settled = true;
      isProcessingRef.current = false;
      onCancel?.();
    };

    const onDismiss = () => {
      // Dismissal may precede success. It is not a terminal auth result, but a
      // previous modal must not clear the next attempt's form/input guard.
      if (authAttemptRef.current !== attempt) {
        return;
      }
      isProcessingRef.current = false;
      onAuthModalDismiss?.();
    };

    try {
      onBeforeAuth?.();
    } catch {
      cancel();
      return;
    }

    try {
      if (!isBiometricsEnabled && !getPasswordIsAutoGeneratedSnapshot()) {
        throw new Error('Biometrics Disabled');
      }

      await apisKeychain.requestGenericPassword({
        purpose: RequestGenericPurpose.DECRYPT_PWD,
        onPlainPassword: async password => {
          await validationHandler?.(password);
          finish();
        },
      });
    } catch (error: any) {
      if (!isCurrentAttempt()) {
        return;
      }
      if (__DEV__) {
        console.error(error);
      }
      if (getPasswordIsAutoGeneratedSnapshot()) {
        cancel();
        return;
      }
      try {
        await AuthenticationModal2024.show({
          title: authTitle || t('page.addressDetail.add-to-whitelist'),
          authType: ['password'],
          onFinished: finish,
          onCancel: cancel,
          onDismiss: onDismiss,
          validationHandler(password) {
            return apisLock.verifyPasswordOrUnlock(password);
          },
        });
      } catch {
        cancel();
      }
    }
  }, [
    onBeforeAuth,
    isBiometricsEnabled,
    authTitle,
    t,
    onFinished,
    onCancel,
    onAuthModalDismiss,
  ]);

  return (
    <Button
      icon={
        isBiometricsEnabled || getPasswordIsAutoGeneratedSnapshot() ? (
          isUsingDevicePasscode ? (
            <RcIconLock
              color={iconColor || colors2024['neutral-InvertHighlight']}
              style={styles.lockIcon}
            />
          ) : isFaceID ? (
            <RcIconKeychainFaceIdCC
              color={iconColor || colors2024['neutral-InvertHighlight']}
              style={styles.lockIcon}
            />
          ) : (
            <RcIconKeychainFingerprintCC
              color={iconColor || colors2024['neutral-InvertHighlight']}
              style={styles.lockIcon}
            />
          )
        ) : (
          // <BiometricsIcon isFaceID={isFaceID} size={22} />
          <RcIconLock
            color={iconColor || colors2024['neutral-InvertHighlight']}
            style={styles.lockIcon}
          />
        )
      }
      onPress={unlockWithBiometrics}
      {...props}
    />
  );
};

export default AuthButton;

const getStyle = createGetStyles2024(ctx => ({
  text: {
    color: 'red',
  },
  biometricsWrapper: {
    width: '100%',
    paddingHorizontal: 16,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 86,
    // ...makeDebugBorder('yellow'),
  },

  biometricsBtns: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    // ...makeDebugBorder('yellow'),
  },
  lockIcon: {
    width: 22,
    height: 22,
  },
}));
