import {
  BOTTOM_BUTTON_TOP_OFFSET,
  getBottomButtonBottomOffset,
} from '@/constant/layout';
import { createGetStyles2024 } from '@/utils/styles';

export const getPerpsProClosePositionSheetStyles = createGetStyles2024(
  ({ colors2024, safeAreaInsets }) => ({
    modal: {
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      overflow: 'hidden',
    },
    background: {
      backgroundColor: colors2024['neutral-bg-1'],
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
    },
    handle: {
      backgroundColor: colors2024['neutral-bg-1'],
      height: 40,
      paddingBottom: 27,
      paddingTop: 9,
    },
    handleIndicator: {
      backgroundColor: colors2024['neutral-line'],
      borderRadius: 2,
      height: 4,
      width: 40,
    },
    sheetView: { height: '100%' },
    container: { height: '100%', paddingHorizontal: 15, paddingTop: 8 },
    title: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 20,
    },
    positionHeader: {
      borderBottomColor: colors2024['neutral-line'],
      borderBottomWidth: 1,
      gap: 8,
      marginTop: 12,
      paddingBottom: 12,
    },
    pairRow: { alignItems: 'center', flexDirection: 'row', gap: 4 },
    pair: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
    },
    longTag: {
      backgroundColor: colors2024['green-light-1'],
      borderColor: colors2024['green-light-2'],
      borderRadius: 2,
      borderWidth: 0.5,
      paddingHorizontal: 4,
      paddingVertical: 1,
    },
    shortTag: {
      backgroundColor: colors2024['red-light-1'],
      borderColor: colors2024['red-light-2'],
      borderRadius: 2,
      borderWidth: 0.5,
      paddingHorizontal: 4,
      paddingVertical: 1,
    },
    longTagText: {
      color: colors2024['green-default'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 10,
      fontWeight: '500',
      lineHeight: 12,
    },
    shortTagText: {
      color: colors2024['red-default'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 10,
      fontWeight: '500',
      lineHeight: 12,
    },
    priceSummaryRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    priceSummaryLabel: {
      color: colors2024['neutral-secondary'],
      fontFamily: 'SF Pro',
      fontSize: 12,
      lineHeight: 16,
    },
    priceSummaryValue: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro',
      fontSize: 12,
      lineHeight: 16,
    },
    form: { gap: 24, marginTop: 24 },
    orderRow: { flexDirection: 'row', gap: 4 },
    priceField: {
      backgroundColor: colors2024['neutral-bg-2'],
      borderRadius: 6,
      flex: 1,
      height: 40,
      justifyContent: 'center',
      minWidth: 0,
      overflow: 'hidden',
      position: 'relative',
    },
    disabledPriceField: {},
    centeredFieldText: {
      color: colors2024['neutral-secondary'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
      textAlign: 'center',
    },
    floatingLabel: {
      color: colors2024['neutral-secondary'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 10,
      left: 8,
      lineHeight: 12,
      position: 'absolute',
      top: 4,
      zIndex: 1,
    },
    priceInput: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      height: 40,
      lineHeight: 18,
      paddingBottom: 0,
      paddingLeft: 8,
      paddingRight: 56,
      paddingTop: 12,
    },
    priceUnit: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      lineHeight: 18,
      position: 'absolute',
      right: 8,
    },
    orderTypeField: {
      alignItems: 'center',
      backgroundColor: colors2024['neutral-bg-2'],
      borderRadius: 8,
      flexDirection: 'row',
      height: 40,
      justifyContent: 'center',
      width: 132,
    },
    orderTypeText: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
    },
    orderTypeSwitch: { marginLeft: 4 },
    amountGroup: { gap: 8 },
    amountField: {
      backgroundColor: colors2024['neutral-bg-2'],
      borderRadius: 6,
      height: 40,
      justifyContent: 'center',
      overflow: 'hidden',
      position: 'relative',
    },
    amountInput: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      height: 40,
      includeFontPadding: false,
      lineHeight: 18,
      paddingBottom: 0,
      paddingLeft: 8,
      paddingRight: 72,
      paddingTop: 12,
      textAlignVertical: 'center',
    },
    amountUnit: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
      position: 'absolute',
      right: 8,
    },
    summary: {
      borderBottomColor: colors2024['neutral-line'],
      borderBottomWidth: 1,
      gap: 8,
      paddingBottom: 12,
    },
    summaryRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    summaryLabel: {
      color: colors2024['neutral-secondary'],
      fontFamily: 'SF Pro',
      fontSize: 12,
      lineHeight: 16,
    },
    summaryValue: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro',
      fontSize: 12,
      lineHeight: 16,
    },
    positiveValue: {
      color: colors2024['green-default'],
      fontFamily: 'SF Pro',
      fontSize: 12,
      lineHeight: 16,
    },
    negativeValue: {
      color: colors2024['red-default'],
      fontFamily: 'SF Pro',
      fontSize: 12,
      lineHeight: 16,
    },
    footer: {
      marginTop: 'auto',
      paddingBottom: getBottomButtonBottomOffset(safeAreaInsets.bottom),
      paddingTop: BOTTOM_BUTTON_TOP_OFFSET,
    },
  }),
);
