import { BOTTOM_BUTTON_TOP_OFFSET } from '@/constant/layout';
import { createGetStyles2024 } from '@/utils/styles';

import {
  getPerpsProBottomSheetChromeStyles,
  resolvePerpsProFieldBackground,
} from '../common/perpsProVisual';
import {
  getPerpsProTintedTagContainerStyle,
  getPerpsProTintedTagTextStyle,
} from '../common/perpsProSemanticTagStyles';

export const getPerpsProClosePositionSheetStyles = createGetStyles2024(
  ({ colors2024, isLight, safeAreaInsets }) => ({
    ...getPerpsProBottomSheetChromeStyles(colors2024),
    sheetView: { height: '100%' },
    container: { height: '100%', paddingHorizontal: 15, paddingTop: 8 },
    title: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 20,
    },
    positionHeader: {
      borderBottomColor: colors2024['neutral-bg-5'],
      borderBottomWidth: 1,
      gap: 8,
      marginTop: 12,
      paddingBottom: 12,
    },
    pairRow: { alignItems: 'center', flexDirection: 'row', gap: 4 },
    pair: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
    },
    longTag: getPerpsProTintedTagContainerStyle(colors2024, 'positive'),
    shortTag: getPerpsProTintedTagContainerStyle(colors2024, 'negative'),
    longTagText: getPerpsProTintedTagTextStyle(colors2024, 'positive'),
    shortTagText: getPerpsProTintedTagTextStyle(colors2024, 'negative'),
    priceSummaryRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    priceSummaryLabel: {
      color: colors2024['neutral-secondary'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
    },
    priceSummaryValue: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
    },
    form: { gap: 24, marginTop: 24 },
    orderRow: { flexDirection: 'row', gap: 4 },
    priceField: {
      backgroundColor: resolvePerpsProFieldBackground({
        darkBackground: colors2024['neutral-bg-2'],
        isLight,
      }),
      borderRadius: 6,
      flex: 1,
      height: 40,
      justifyContent: 'center',
      minWidth: 0,
      overflow: 'hidden',
      position: 'relative',
    },
    disabledPriceField: {},
    centeredFieldText: {
      color: colors2024['neutral-secondary'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
      textAlign: 'center',
    },
    floatingLabel: {
      color: colors2024['neutral-secondary'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 10,
      left: 8,
      lineHeight: 12,
      position: 'absolute',
      top: 4,
      zIndex: 1,
    },
    priceInput: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      height: 40,
      lineHeight: 18,
      paddingBottom: 0,
      paddingLeft: 8,
      paddingRight: 56,
      paddingTop: 12,
    },
    priceUnit: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      lineHeight: 18,
      position: 'absolute',
      right: 8,
    },
    orderTypeField: {
      alignItems: 'center',
      backgroundColor: resolvePerpsProFieldBackground({
        darkBackground: colors2024['neutral-bg-2'],
        isLight,
      }),
      borderRadius: 8,
      flexDirection: 'row',
      height: 40,
      justifyContent: 'center',
      width: 132,
    },
    orderTypeText: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
    },
    orderTypeSwitch: { marginLeft: 4 },
    amountGroup: { gap: 8 },
    amountField: {
      backgroundColor: resolvePerpsProFieldBackground({
        darkBackground: colors2024['neutral-bg-2'],
        isLight,
      }),
      borderRadius: 6,
      height: 40,
      justifyContent: 'center',
      overflow: 'hidden',
      position: 'relative',
    },
    amountInput: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      height: 40,
      includeFontPadding: false,
      lineHeight: 18,
      paddingBottom: 0,
      paddingLeft: 8,
      paddingRight: 72,
      paddingTop: 12,
      textAlignVertical: 'center',
    },
    amountUnit: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
      position: 'absolute',
      right: 8,
    },
    summary: {
      borderBottomColor: colors2024['neutral-bg-5'],
      borderBottomWidth: 1,
      gap: 8,
      paddingBottom: 12,
    },
    summaryRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    summaryLabel: {
      color: colors2024['neutral-secondary'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
    },
    summaryValue: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
    },
    positiveValue: {
      color: colors2024['green-default'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
    },
    negativeValue: {
      color: colors2024['red-default'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
    },
    footer: {
      marginTop: 'auto',
      paddingBottom: Math.max(40, safeAreaInsets.bottom),
      paddingTop: BOTTOM_BUTTON_TOP_OFFSET,
    },
  }),
);
