import { useCallback, useEffect, useMemo } from 'react';
import { BIOMETRY_TYPE } from '@rabby-wallet/react-native-keychain';
import { toast, toastLoading } from '@/components2024/Toast';
import { apisKeychain } from '@/core/apis';
import {
  KEYCHAIN_AUTH_TYPES,
  RequestGenericPurpose,
  getAuthenticationType,
  isAuthenticatedByBiometrics,
  parseKeychainError,
  type KeychainSupportedBiometryType,
} from '@/core/apis/keychain';
import { useTranslation } from 'react-i18next';
import {
  ValidationBehaviorProps,
  parseValidationBehavior,
} from '@/core/apis/lock';
import { Alert, Vibration } from 'react-native';
import { IExtractFromPromise } from '@/utils/type';
import { IS_IOS } from '@/core/native/utils';
import { preferenceService } from '@/core/services';
import { zCreate } from '@/core/utils/reexports';
import {
  resolveValFromUpdater,
  runIIFEFunc,
  UpdaterOrPartials,
} from '@/core/utils/store';
import { useShallow } from 'zustand/react/shallow';

type BiometricsInfoState = {
  authEnabled: boolean;
  supportedBiometryType: KeychainSupportedBiometryType;
  devicePasscodeAvailable: boolean;
};
const biometricsInfoStore = zCreate<BiometricsInfoState>(() => ({
  authEnabled: isAuthenticatedByBiometrics(),
  supportedBiometryType: null,
  devicePasscodeAvailable: false,
}));
export function setBiometrics(
  valOrFunc: UpdaterOrPartials<BiometricsInfoState>,
) {
  biometricsInfoStore.setState(
    prev => resolveValFromUpdater(prev, valOrFunc).newVal,
  );
}
async function getDevicePasscodeAvailable() {
  if (IS_IOS) {
    return false;
  }

  return apisKeychain.isPasscodeAuthAvailable().catch(() => false);
}

async function fetchSystemAuthAvailability() {
  const [supportedBiometryType, devicePasscodeAvailable] = await Promise.all([
    apisKeychain.getSupportedBiometryType().catch(() => null),
    getDevicePasscodeAvailable(),
  ]);

  return { supportedBiometryType, devicePasscodeAvailable };
}

runIIFEFunc(() => {
  fetchSystemAuthAvailability().then(systemAuth => {
    setBiometrics(prev => ({ ...prev, ...systemAuth }));
  });
});

export function useBiometricsComputed() {
  const authEnabled = biometricsInfoStore(s => s.authEnabled);
  const supportedBiometryType = biometricsInfoStore(
    s => s.supportedBiometryType,
  );
  const devicePasscodeAvailable = biometricsInfoStore(
    s => s.devicePasscodeAvailable,
  );
  const { t } = useTranslation();

  const computed = useMemo(() => {
    const isFaceID = supportedBiometryType === BIOMETRY_TYPE.FACE_ID;
    const authType = getAuthenticationType();
    const isAndroidBiometricsOrPasscode =
      !IS_IOS && authType === KEYCHAIN_AUTH_TYPES.BIOMETRICS_OR_PASSCODE;
    const canFallbackToDevicePasscode =
      authEnabled && isAndroidBiometricsOrPasscode && devicePasscodeAvailable;
    const passwordIsAutoGenerated =
      !!preferenceService.store.passwordIsAutoGenerated;

    // When password is auto-generated and biometrics have no permission/enrollment,
    // the user relies on device passcode for authentication
    const isUsingDevicePasscode =
      !supportedBiometryType &&
      (passwordIsAutoGenerated ||
        (devicePasscodeAvailable && canFallbackToDevicePasscode));
    const defaultTypeLabel = isUsingDevicePasscode
      ? IS_IOS
        ? 'Device Passcode'
        : 'Device PIN'
      : isFaceID
      ? t('page.setting.faceId')
      : IS_IOS
      ? t('page.setting.touchId')
      : t('page.setting.fingerPrint');

    return {
      isBiometricsEnabled:
        authEnabled && (!!supportedBiometryType || canFallbackToDevicePasscode),
      settingsAuthEnabled: authEnabled,
      couldSetupBiometrics: !!supportedBiometryType,
      supportedBiometryType,
      devicePasscodeAvailable,
      defaultTypeLabel,
      isFaceID,
      isUsingDevicePasscode,
    };
  }, [authEnabled, supportedBiometryType, devicePasscodeAvailable, t]);

  return computed;
}

const isFetchingBiometricsRef = { current: false };
const fetchBiometrics = async () => {
  if (isFetchingBiometricsRef.current) return;

  isFetchingBiometricsRef.current = true;
  try {
    let systemAuth = {
      supportedBiometryType: null as KeychainSupportedBiometryType,
      devicePasscodeAvailable: false,
    };
    let didFetchSupportedType = false;
    try {
      systemAuth = await fetchSystemAuthAvailability();
      didFetchSupportedType = true;
    } catch (error) {
      console.error(error);
    }
    setBiometrics(prev => {
      if (!didFetchSupportedType) {
        return prev;
      }
      const nextAuthEnabled = isAuthenticatedByBiometrics();
      // if (prev.authEnabled && !supportedType) {
      //   toast.info(
      //     'Biometrics authentication disabled because no valid biometric data found.',
      //   );
      // }
      return {
        ...prev,
        ...systemAuth,
        authEnabled: nextAuthEnabled,
      };
    });
  } catch (error) {
    console.error(error);
  } finally {
    isFetchingBiometricsRef.current = false;
  }
};

const toggleBiometrics = async <T extends boolean>(
  nextEnabled: T,
  input: {
    tipLoading?: boolean;
    authenticationType?: KEYCHAIN_AUTH_TYPES;
  } & (T extends true
    ? { validatedPassword: string }
    : { validatedPassword?: undefined }),
) => {
  const { validatedPassword, tipLoading, authenticationType } = input;
  let changed = false;

  const hideToast = !tipLoading
    ? null
    : toastLoading(`${nextEnabled ? 'Enabling' : 'Disabling'} biometrics`);

  const reset = async () => {
    await apisKeychain.resetGenericPassword();
    setBiometrics(prev => ({ ...prev, authEnabled: false }));
  };

  try {
    if (!nextEnabled) {
      await reset();
      changed = true;
    } else {
      if (!validatedPassword) {
        throw new Error('Validated password is required to enable biometrics.');
      }

      await apisKeychain.setGenericPassword(
        validatedPassword,
        authenticationType ??
          apisKeychain.getDefaultBiometricsAuthenticationType(),
      );
      const requestResult = await apisKeychain.requestGenericPassword({
        purpose: RequestGenericPurpose.VERIFY,
      });
      if (!requestResult) {
        await reset();
      } else if (requestResult && requestResult.actionSuccess) {
        setBiometrics(prev => ({ ...prev, authEnabled: true }));
        changed = true;
      }
    }
  } catch (error: any) {
    if (nextEnabled) {
      await reset();
      return false;
    }

    const parsedInfo = parseKeychainError(error);
    if (parsedInfo.isCancelledByUser || (__DEV__ && parsedInfo.sysMessage)) {
      toast.show(parsedInfo.sysMessage);
    } else {
      toast.show(error?.message);
    }
  } finally {
    hideToast?.();
    await fetchBiometrics();
  }

  return changed && biometricsInfoStore.getState().authEnabled === nextEnabled;
};

export const storeApisBiometrics = {
  fetchBiometrics,
  toggleBiometrics,
};

export function useBiometrics(options?: { autoFetch?: boolean }) {
  const biometrics = biometricsInfoStore(
    useShallow(s => ({
      authEnabled: s.authEnabled,
      supportedBiometryType: s.supportedBiometryType,
      devicePasscodeAvailable: s.devicePasscodeAvailable,
    })),
  );

  useEffect(() => {
    if (options?.autoFetch) {
      fetchBiometrics();
    }
  }, [options?.autoFetch]);

  const computed = useBiometricsComputed();

  return {
    biometrics,
    computed,
    fetchBiometrics,
    toggleBiometrics,
  };
}

type BiometricsStubModalState = {
  status: 'idle' | 'preparing' | 'processing' | 'success' | 'failed';
  lastStubBehaviors: ValidationBehaviorProps | null;
};
const biometricsStubModalState = zCreate<BiometricsStubModalState>(() => ({
  status: 'idle',
  lastStubBehaviors: {},
}));
export function setBiometricsStubModalState(
  valOrFunc: UpdaterOrPartials<BiometricsStubModalState>,
) {
  biometricsStubModalState.setState(
    prev => resolveValFromUpdater(prev, valOrFunc).newVal,
  );
}
function getBiometricsStubModalState() {
  return biometricsStubModalState.getState();
}

export function useVerifyByBiometrics() {
  const biometricsStatus = biometricsStubModalState(s => s.status);
  const { t } = useTranslation();

  const {
    computed: { isBiometricsEnabled },
  } = useBiometrics();

  const verifyByBiometrics = useCallback(
    async (options?: ValidationBehaviorProps) => {
      if (!isBiometricsEnabled) {
        toast.info(
          t('component.AuthenticationModals.processBiometrics.notEnabled'),
        );
        return;
      }

      const bioStubModalState = getBiometricsStubModalState();

      if (bioStubModalState.status === 'processing') return;
      setBiometricsStubModalState(prev => ({ ...prev, status: 'processing' }));

      const behaviors = options || { ...bioStubModalState.lastStubBehaviors };
      const defaultFinished = () => {
        setTimeout(() => {
          setBiometricsStubModalState(prev => ({ ...prev, status: 'idle' }));
        }, 250);
      };
      const { validationHandler, onFinished = defaultFinished } =
        parseValidationBehavior(behaviors);

      let rawPassword = '';
      let verifyResult: IExtractFromPromise<
        ReturnType<typeof apisKeychain.requestGenericPassword>
      > = null;
      try {
        verifyResult = await apisKeychain.requestGenericPassword({
          purpose: RequestGenericPurpose.DECRYPT_PWD,
          onPlainPassword: password => {
            rawPassword = password;
          },
        });
      } catch (error) {
        __DEV__ && console.debug(error);
        const parsedInfo = parseKeychainError(error);
        if (
          parsedInfo.isCancelledByUser ||
          (__DEV__ && parsedInfo.sysMessage)
        ) {
          toast.info(parsedInfo.sysMessage);
        } else {
          toast.info(
            t('component.AuthenticationModals.processBiometrics.authFailed'),
          );
        }
        // vibration here
        if (error) Vibration.vibrate([100], false);
      }

      try {
        if (!verifyResult || !verifyResult.actionSuccess || !rawPassword) {
          setBiometricsStubModalState(prev => ({ ...prev, status: 'failed' }));
        } else {
          await validationHandler?.(rawPassword);
          setBiometricsStubModalState(prev => ({ ...prev, status: 'success' }));
          onFinished?.({ getValidatedPassword: () => rawPassword });
        }
      } catch (error) {
        setBiometricsStubModalState(prev => ({ ...prev, status: 'failed' }));
      }
    },
    [isBiometricsEnabled, t],
  );

  const abortBiometricsVerification = useCallback(() => {
    setBiometricsStubModalState(prev => ({ ...prev, status: 'idle' }));
  }, []);

  const startBiometricsVerification = useCallback(
    (options?: ValidationBehaviorProps) => {
      setBiometricsStubModalState(prev => ({
        ...prev,
        lastStubBehaviors: { ...options },
        status: 'preparing',
      }));
    },
    [],
  );

  const { isProcessBiometrics, shouldShowStubModal } = useMemo(() => {
    return {
      isProcessBiometrics: biometricsStatus === 'processing',
      shouldShowStubModal: biometricsStatus !== 'idle',
    };
  }, [biometricsStatus]);

  return {
    isProcessBiometrics,
    shouldShowStubModal,
    verifyByBiometrics,
    startBiometricsVerification,
    abortBiometricsVerification,
  };
}
