describe('hooks/biometrics', () => {
  const KEYCHAIN_AUTH_TYPES = {
    APPLICATION_PASSWORD: 0,
    BIOMETRICS: 1,
    PASSCODE: 2,
    REMEMBER_ME: 3,
    BIOMETRICS_OR_PASSCODE: 4,
  };
  const RequestGenericPurpose = {
    VERIFY: 1,
    DECRYPT_PWD: 11,
  };

  const setup = async ({
    authType = KEYCHAIN_AUTH_TYPES.BIOMETRICS_OR_PASSCODE,
    authenticatedByBiometrics = true,
    supportedBiometryType = null as string | null,
    passcodeAuthAvailable = true,
    passwordIsAutoGenerated = false,
  } = {}) => {
    jest.resetModules();

    const mockSetGenericPassword = jest.fn(async () => undefined);
    const mockRequestGenericPassword = jest.fn(async () => ({
      actionSuccess: true,
    }));
    const mockResetGenericPassword = jest.fn(async () => true);
    const mockGetSupportedBiometryType = jest.fn(
      async () => supportedBiometryType,
    );
    const mockIsPasscodeAuthAvailable = jest.fn(
      async () => passcodeAuthAvailable,
    );
    const mockGetKeychainDebugState = jest.fn(async () => ({
      platform: 'android',
      debugSupported: true,
      hasEntry: true,
      hasUsername: true,
      hasPassword: true,
      sourceLabel: 'test-keychain',
      resolvedCipherStorageName: 'KeystoreAESGCM_NoAuth',
      hasKeystoreAlias: true,
    }));

    jest.doMock('@rabby-wallet/react-native-keychain', () => ({
      BIOMETRY_TYPE: {
        FACE_ID: 'FaceID',
      },
    }));
    jest.doMock('react-i18next', () => ({
      useTranslation: () => ({
        t: (key: string) => key,
      }),
    }));
    jest.doMock('@/core/native/utils', () => ({
      IS_ANDROID: true,
      IS_IOS: false,
    }));
    jest.doMock('@/constant', () => ({
      isNonPublicProductionEnv: true,
    }));
    jest.doMock('@/core/storage/mmkv', () => ({
      zustandByMMKV: <T extends object>(_key: string, initialState: T) => {
        let state = initialState;
        const store = ((selector: (input: T) => unknown) =>
          selector(state)) as ((selector: (input: T) => unknown) => unknown) & {
          getState: () => T;
          setState: (updater: T | ((prev: T) => T)) => void;
        };

        store.getState = () => state;
        store.setState = updater => {
          state =
            typeof updater === 'function'
              ? (updater as (prev: T) => T)(state)
              : updater;
        };
        return store;
      },
    }));
    jest.doMock('@/core/apis/keychain', () => ({
      KEYCHAIN_AUTH_TYPES,
      RequestGenericPurpose,
      getAuthenticationType: jest.fn(() => authType),
      isAuthenticatedByBiometrics: jest.fn(() => authenticatedByBiometrics),
      parseKeychainError: jest.fn(() => ({
        isCancelledByUser: false,
        sysMessage: '',
      })),
    }));
    jest.doMock('@/core/apis', () => ({
      apisKeychain: {
        KEYCHAIN_AUTH_TYPES,
        RequestGenericPurpose,
        getSupportedBiometryType: mockGetSupportedBiometryType,
        isPasscodeAuthAvailable: mockIsPasscodeAuthAvailable,
        getKeychainDebugState: mockGetKeychainDebugState,
        getDefaultBiometricsAuthenticationType: jest.fn(
          () => KEYCHAIN_AUTH_TYPES.BIOMETRICS_OR_PASSCODE,
        ),
        setGenericPassword: mockSetGenericPassword,
        requestGenericPassword: mockRequestGenericPassword,
        resetGenericPassword: mockResetGenericPassword,
      },
    }));
    jest.doMock('@/core/apis/lock', () => ({
      parseValidationBehavior: jest.fn(),
    }));
    jest.doMock('@/core/services', () => ({
      preferenceService: {
        store: {
          passwordIsAutoGenerated,
        },
      },
    }));
    jest.doMock('@/components2024/Toast', () => ({
      toast: {
        show: jest.fn(),
        info: jest.fn(),
        success: jest.fn(),
        error: jest.fn(),
      },
      toastLoading: jest.fn(() => jest.fn()),
    }));
    jest.doMock('@/utils/logger', () => ({
      logger: {
        info: jest.fn(),
        warn: jest.fn(),
      },
    }));
    jest.doMock('react-native-haptic-feedback', () => ({
      trigger: jest.fn(),
    }));

    const module = require('./biometrics') as typeof import('./biometrics');
    await Promise.resolve();

    return {
      module,
      mockSetGenericPassword,
      mockRequestGenericPassword,
      mockGetSupportedBiometryType,
      mockIsPasscodeAuthAvailable,
    };
  };

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('allows settings setup when biometric enrollment is gone but Android passcode is available', async () => {
    const { module } = await setup();

    const computed = module.computeBiometricsState({
      authEnabled: false,
      supportedBiometryType: null,
      devicePasscodeAvailable: true,
      authType: KEYCHAIN_AUTH_TYPES.BIOMETRICS_OR_PASSCODE,
      passwordIsAutoGenerated: false,
      t: (key: string) => key,
      isIOS: false,
    });

    expect(computed.couldSetupBiometrics).toBe(false);
    expect(computed.couldSetupSystemAuth).toBe(true);
    expect(computed.isBiometricsEnabled).toBe(false);
    expect(computed.isUsingDevicePasscode).toBe(false);
  });

  it('enables passcode-capable system auth when only Android passcode is available', async () => {
    const {
      module,
      mockSetGenericPassword,
      mockRequestGenericPassword,
      mockGetSupportedBiometryType,
      mockIsPasscodeAuthAvailable,
    } = await setup();

    const changed = await module.storeApisBiometrics.toggleBiometrics(true, {
      validatedPassword: 'plain-password',
    });

    expect(changed).toBe(true);
    expect(mockSetGenericPassword).toHaveBeenCalledWith(
      'plain-password',
      KEYCHAIN_AUTH_TYPES.BIOMETRICS_OR_PASSCODE,
    );
    expect(mockRequestGenericPassword).toHaveBeenCalledWith({
      purpose: RequestGenericPurpose.VERIFY,
    });
    expect(mockGetSupportedBiometryType).toHaveBeenCalled();
    expect(mockIsPasscodeAuthAvailable).toHaveBeenCalled();

    const computed = module.computeBiometricsState({
      authEnabled: true,
      supportedBiometryType: null,
      devicePasscodeAvailable: true,
      authType: KEYCHAIN_AUTH_TYPES.BIOMETRICS_OR_PASSCODE,
      passwordIsAutoGenerated: false,
      t: (key: string) => key,
      isIOS: false,
    });
    expect(computed.isBiometricsEnabled).toBe(true);
    expect(computed.isUsingDevicePasscode).toBe(true);
  });

  it('mocks no biometric enrollment while Android device passcode remains available', async () => {
    const { module } = await setup({
      supportedBiometryType: 'Fingerprint',
      passcodeAuthAvailable: false,
    });

    const changed = module.setBiometricsSystemAuthDebugMode(
      module.BIOMETRICS_SYSTEM_AUTH_DEBUG_MODES.PASSCODE_ONLY,
    );

    expect(changed).toBe(true);
    expect(
      module.applyBiometricsSystemAuthDebugMock({
        supportedBiometryType: null,
        devicePasscodeAvailable: false,
      }),
    ).toEqual({
      supportedBiometryType: null,
      devicePasscodeAvailable: true,
    });
  });

  it('mocks no usable system authentication', async () => {
    const { module } = await setup({
      supportedBiometryType: 'Fingerprint',
      passcodeAuthAvailable: true,
    });

    const changed = module.setBiometricsSystemAuthDebugMode(
      module.BIOMETRICS_SYSTEM_AUTH_DEBUG_MODES.NONE,
    );

    expect(changed).toBe(true);
    expect(
      module.applyBiometricsSystemAuthDebugMock({
        supportedBiometryType: null,
        devicePasscodeAvailable: true,
      }),
    ).toEqual({
      supportedBiometryType: null,
      devicePasscodeAvailable: false,
    });
  });
});
