export const PERPS_PRO_HISTORY_ORDERS_LIMIT = 2_000;
export const PERPS_PRO_HISTORY_TRADE_INITIAL_LIMIT = 2_000;
export const PERPS_PRO_HISTORY_TRADE_LIMIT = 10_000;
export const PERPS_PRO_HISTORY_CASHFLOW_INITIAL_LIMIT = 2_000;
export const PERPS_PRO_HISTORY_CASHFLOW_LIMIT = 5_000;

export const PERPS_PRO_HISTORY_WINDOW_MS = 30 * 24 * 60 * 60 * 1_000;

export const PERPS_PRO_HISTORY_TRADE_PAGE_HINT = 2_000;
export const PERPS_PRO_HISTORY_LEDGER_PAGE_HINT = 500;
export const PERPS_PRO_HISTORY_MAX_WINDOW_REQUESTS = 64;
export const PERPS_PRO_HISTORY_MAX_NARROW_ATTEMPTS = 24;

export const PERPS_PRO_HISTORY_FEE_TIPS_OWNER = 'perps-pro-history-fee';
