import {
  BOTTOM_BUTTON_TOP_OFFSET,
  getBottomButtonBottomOffset,
} from '@/constant/layout';
import { createGetStyles2024 } from '@/utils/styles';
import {
  getPerpsProDialogStyles,
  PERPS_PRO_DIALOG_HEAVY_TEXT_STYLE,
} from '../common/perpsProDialogVisual';

export const getPerpsProTransferSheetStyles = createGetStyles2024(
  ({ colors2024, safeAreaInsets }) => ({
    ...getPerpsProDialogStyles(colors2024, safeAreaInsets.bottom),
    sheetView: { height: '100%' },
    container: { height: '100%', paddingHorizontal: 16, paddingTop: 8 },
    content: { gap: 8, marginTop: 24 },
    section: { gap: 8 },
    sectionLabel: {
      color: colors2024['neutral-foot'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
    },
    directionCard: {
      backgroundColor: colors2024['neutral-bg-1'],
      borderRadius: 12,
      height: 92,
      paddingHorizontal: 16,
      paddingVertical: 4,
    },
    directionRow: { alignItems: 'center', flexDirection: 'row', height: 42 },
    directionLabel: {
      color: colors2024['neutral-secondary'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
      width: 59,
    },
    directionValue: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
    },
    amountHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    balance: {
      color: colors2024['neutral-body'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
    },
    amountField: {
      alignItems: 'center',
      backgroundColor: colors2024['neutral-bg-1'],
      borderRadius: 16,
      flexDirection: 'row',
      height: 82,
      paddingHorizontal: 16,
    },
    amountPrefix: {
      ...PERPS_PRO_DIALOG_HEAVY_TEXT_STYLE,
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 36,
      lineHeight: 42,
    },
    amountInput: {
      ...PERPS_PRO_DIALOG_HEAVY_TEXT_STYLE,
      color: colors2024['neutral-title-1'],
      flex: 1,
      fontFamily: 'SF Pro Rounded',
      fontSize: 36,
      height: 82,
      lineHeight: 42,
      minWidth: 0,
      padding: 0,
    },
    tokenPill: {
      alignItems: 'center',
      backgroundColor: colors2024['neutral-bg-5'],
      borderRadius: 8,
      flexDirection: 'row',
      gap: 6,
      height: 40,
      justifyContent: 'center',
      marginLeft: 8,
      width: 99,
    },
    tokenText: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 20,
    },
    shortcuts: { flexDirection: 'row', gap: 8, marginTop: 4 },
    shortcut: {
      alignItems: 'center',
      backgroundColor: colors2024['neutral-bg-1'],
      borderRadius: 6,
      flex: 1,
      height: 40,
      justifyContent: 'center',
    },
    shortcutDisabled: { opacity: 0.55 },
    shortcutText: {
      color: colors2024['neutral-body'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
    },
    footer: {
      marginTop: 'auto',
      paddingHorizontal: 4,
      paddingBottom: getBottomButtonBottomOffset(safeAreaInsets.bottom),
      paddingTop: BOTTOM_BUTTON_TOP_OFFSET * 2,
    },
  }),
);
