import {
  BOTTOM_BUTTON_TOP_OFFSET,
  getBottomButtonBottomOffset,
} from '@/constant/layout';
import { createGetStyles2024 } from '@/utils/styles';

export const getPerpsProTransferSheetStyles = createGetStyles2024(
  ({ colors2024, safeAreaInsets }) => ({
    sheetView: { height: '100%' },
    container: { height: '100%', paddingHorizontal: 15, paddingTop: 8 },
    title: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 20,
    },
    content: { gap: 24, marginTop: 16 },
    section: { gap: 8 },
    sectionLabel: {
      color: colors2024['neutral-body'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
    },
    directionCard: {
      backgroundColor: colors2024['neutral-bg-2'],
      borderRadius: 6,
      height: 76,
      justifyContent: 'center',
      paddingHorizontal: 8,
      position: 'relative',
    },
    directionRow: { alignItems: 'center', flexDirection: 'row', height: 34 },
    directionLabel: {
      color: colors2024['neutral-foot'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
      width: 41,
    },
    directionValue: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 18,
    },
    directionIcon: {
      alignItems: 'center',
      height: 16,
      justifyContent: 'center',
      position: 'absolute',
      right: 16,
      top: 30,
      transform: [{ rotate: '90deg' }],
      width: 16,
    },
    amountHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    balance: {
      color: colors2024['neutral-body'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
    },
    amountField: {
      alignItems: 'center',
      backgroundColor: colors2024['neutral-bg-2'],
      borderRadius: 6,
      flexDirection: 'row',
      height: 72,
      paddingHorizontal: 16,
    },
    amountInput: {
      color: colors2024['neutral-title-1'],
      flex: 1,
      fontFamily: 'SF Pro Rounded',
      fontSize: 28,
      fontWeight: '700',
      height: 72,
      lineHeight: 36,
      minWidth: 0,
      padding: 0,
    },
    tokenPill: {
      alignItems: 'center',
      borderColor: colors2024['neutral-line'],
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 6,
      height: 40,
      justifyContent: 'center',
      marginLeft: 8,
      paddingHorizontal: 12,
    },
    tokenText: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 20,
    },
    shortcuts: { flexDirection: 'row', gap: 8 },
    shortcut: {
      alignItems: 'center',
      backgroundColor: colors2024['neutral-bg-2'],
      borderRadius: 6,
      flex: 1,
      height: 40,
      justifyContent: 'center',
    },
    shortcutDisabled: { opacity: 0.55 },
    shortcutText: {
      color: colors2024['neutral-title-1'],
      fontFamily: 'SF Pro Rounded',
      fontSize: 12,
      lineHeight: 16,
    },
    footer: {
      marginTop: 'auto',
      paddingBottom: getBottomButtonBottomOffset(safeAreaInsets.bottom),
      paddingTop: BOTTOM_BUTTON_TOP_OFFSET,
    },
  }),
);
