name: Hash Validate RN App

on:
  push:
    branches:
      - feat/hash-check
  workflow_dispatch:

jobs:
  # --- Job 1: 构建 Android ---
  build-android:
    name: Build Android & Generate Hash
    runs-on: ubuntu-latest
    outputs:
      android_hash: ${{ steps.generate_hash.outputs.hash }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: '[Linux] Setup Nodejs and Yarn'
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: '[Linux] Setup Ruby & Fastlane'
        uses: heisenberg-2077/setup-ruby@master
        with:
          ruby-version: '2.7.2'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: '[Linux] Setup Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: '[Linux] Setup Android SDK'
        uses: android-actions/setup-android@v3

      - name: Validate Android App
        id: generate_hash
        run: |
          cd apps/mobile
          GENERATED_HASH=$(./scripts/validate-hash/run.sh android | tee /dev/stderr | grep 'Android Hash:' | awk '{print $NF}')
          echo "hash=${GENERATED_HASH}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          path: apps/mobile/validation_exports_*
          retention-days: 1

      - name: Clean logs
        run: |
          rm -rf apps/mobile/validation_exports_*

  # --- Job 2: 构建 iOS ---
  build-ios:
    name: Build iOS & Generate Hash
    runs-on: macos-latest

    outputs:
      ios_hash: ${{ steps.generate_hash.outputs.hash }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: '[macOS] Setup Xcode'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Validate iOS App
        id: generate_hash
        run: |
          cd apps/mobile
          GENERATED_HASH=$(./scripts/validate-hash/run.sh ios | tee /dev/stderr | grep 'iOS Hash:' | awk '{print $NF}')
          echo "hash=${GENERATED_HASH}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          path: apps/mobile/validation_exports_*
          retention-days: 1

      - name: Clean logs
        run: |
          rm -rf apps/mobile/validation_exports_*

  # --- Job 3: 结合 Hash ---
  combine-hashes:
    name: Combine Hashes
    needs: [build-android, build-ios]
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Get Hashes from previous jobs
        run: |
          echo "Android Hash: ${{ needs.build-android.outputs.android_hash }}"
          echo "iOS Hash: ${{ needs.build-ios.outputs.ios_hash }}"

      - name: Generate Final Hash
        run: |
          HASH_A="${{ needs.build-android.outputs.android_hash }}"
          HASH_I="${{ needs.build-ios.outputs.ios_hash }}"

          if [ -z "$HASH_A" ] || [ -z "$HASH_I" ]; then
            echo "Error: One of the required hashes is missing."
            exit 1
          fi

          FINAL_HASH=$(printf "%s\n%s" "$HASH_I" "$HASH_A" | sort | shasum -a 256 | awk '{print $1}')

          echo "Final Combined Hash: ${FINAL_HASH}"
