name: Mobile Jest

on:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/mobile_jest.yml'
      - 'package.json'
      - 'yarn.lock'
      - '.yarn/**'
      - 'tests/**'
      - 'packages/**'
      - 'apps/mobile/**'
  pull_request:
    branches: [develop]
    paths:
      - '.github/workflows/mobile_jest.yml'
      - 'package.json'
      - 'yarn.lock'
      - '.yarn/**'
      - 'tests/**'
      - 'packages/**'
      - 'apps/mobile/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash -ieol pipefail {0}

concurrency:
  group: mobile-jest-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mobile_jest:
    name: apps/mobile jest
    runs-on:
      - ubuntu-latest
    timeout-minutes: 20
    permissions:
      actions: read
      contents: read
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
      YARN_ENABLE_HARDENED_MODE: '0'

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run apps/mobile Jest
        run: yarn workspace rabby-mobile test --runInBand
