import { planBiometricAuthStateRecovery } from './biometricAuthStateRecovery';

describe('planBiometricAuthStateRecovery', () => {
  it('keeps a complete biometric-only state unchanged', () => {
    expect(
      planBiometricAuthStateRecovery({
        passwordState: { version: 1, origin: 'auto-generated' },
        passwordIsAutoGenerated: true,
        isBiometricAuthenticationType: true,
      }),
    ).toEqual({
      expectedPasswordIsAutoGenerated: true,
      shouldResetKeychain: false,
      shouldCompleteDisableTransition: false,
      reason: 'consistent',
    });
  });

  it('repairs the preference mirror from authoritative keyring state', () => {
    expect(
      planBiometricAuthStateRecovery({
        passwordState: { version: 1, origin: 'user' },
        passwordIsAutoGenerated: true,
        isBiometricAuthenticationType: false,
      }),
    ).toEqual({
      expectedPasswordIsAutoGenerated: false,
      shouldResetKeychain: false,
      shouldCompleteDisableTransition: false,
      reason: 'keyring-password-state',
    });
  });

  it('finishes an interrupted biometric disable after password persistence', () => {
    expect(
      planBiometricAuthStateRecovery({
        passwordState: {
          version: 1,
          origin: 'user',
          pendingAuthTransition: 'disable-biometrics',
        },
        passwordIsAutoGenerated: true,
        isBiometricAuthenticationType: true,
      }),
    ).toEqual({
      expectedPasswordIsAutoGenerated: false,
      shouldResetKeychain: true,
      shouldCompleteDisableTransition: true,
      reason: 'pending-disable-biometrics',
    });
  });

  it('completes an interrupted disable idempotently after keychain reset', () => {
    expect(
      planBiometricAuthStateRecovery({
        passwordState: {
          version: 1,
          origin: 'user',
          pendingAuthTransition: 'disable-biometrics',
        },
        passwordIsAutoGenerated: false,
        isBiometricAuthenticationType: false,
      }),
    ).toEqual({
      expectedPasswordIsAutoGenerated: false,
      shouldResetKeychain: false,
      shouldCompleteDisableTransition: true,
      reason: 'pending-disable-biometrics',
    });
  });

  it('heals the legacy issue 883 state without metadata', () => {
    expect(
      planBiometricAuthStateRecovery({
        passwordIsAutoGenerated: true,
        isBiometricAuthenticationType: false,
      }),
    ).toEqual({
      expectedPasswordIsAutoGenerated: false,
      nextPasswordState: { version: 1, origin: 'user' },
      shouldResetKeychain: false,
      shouldCompleteDisableTransition: false,
      reason: 'legacy-interrupted-disable',
    });
  });

  it('does not reinterpret a valid legacy biometric-only state', () => {
    expect(
      planBiometricAuthStateRecovery({
        passwordIsAutoGenerated: true,
        isBiometricAuthenticationType: true,
      }),
    ).toEqual({
      shouldResetKeychain: false,
      shouldCompleteDisableTransition: false,
      reason: 'consistent',
    });
  });
});
