import type { KeyringPasswordState } from '@rabby-wallet/service-keyring';

export type BiometricAuthRecoveryInput = {
  passwordState?: KeyringPasswordState;
  passwordIsAutoGenerated: boolean;
  isBiometricAuthenticationType: boolean;
};

export type BiometricAuthRecoveryPlan = {
  expectedPasswordIsAutoGenerated?: boolean;
  nextPasswordState?: KeyringPasswordState;
  shouldResetKeychain: boolean;
  shouldCompleteDisableTransition: boolean;
  reason:
    | 'consistent'
    | 'keyring-password-state'
    | 'pending-disable-biometrics'
    | 'legacy-interrupted-disable';
};

export function planBiometricAuthStateRecovery({
  passwordState,
  passwordIsAutoGenerated,
  isBiometricAuthenticationType,
}: BiometricAuthRecoveryInput): BiometricAuthRecoveryPlan {
  if (passwordState?.pendingAuthTransition === 'disable-biometrics') {
    return {
      expectedPasswordIsAutoGenerated: false,
      shouldResetKeychain: isBiometricAuthenticationType,
      shouldCompleteDisableTransition: true,
      reason: 'pending-disable-biometrics',
    };
  }

  if (passwordState) {
    const expectedPasswordIsAutoGenerated =
      passwordState.origin === 'auto-generated';
    return {
      expectedPasswordIsAutoGenerated,
      shouldResetKeychain: false,
      shouldCompleteDisableTransition: false,
      reason:
        expectedPasswordIsAutoGenerated === passwordIsAutoGenerated
          ? 'consistent'
          : 'keyring-password-state',
    };
  }

  if (passwordIsAutoGenerated && !isBiometricAuthenticationType) {
    return {
      expectedPasswordIsAutoGenerated: false,
      nextPasswordState: {
        version: 1,
        origin: 'user',
      },
      shouldResetKeychain: false,
      shouldCompleteDisableTransition: false,
      reason: 'legacy-interrupted-disable',
    };
  }

  return {
    shouldResetKeychain: false,
    shouldCompleteDisableTransition: false,
    reason: 'consistent',
  };
}
